</br>
    </br>
    </br>
    </br>
<div class="container mt-5">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 30rem;">
      <div class="card-body">

            <div class="d-flex justify-content-center">
          		<img src="/img/teach.png" style="width: 6rem;" />
        	</div>

        <div class="row">
          <div class="col-lg-12">
            <h2 class="text-center">Dados Guardado</h2>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-12">
            
            <form action="/registra" method="post">
            <div class="d-flex justify-content-center">
                <img src="/img/bemvindo.png" alt="">
        	</div>
            <h4 class="text-center"><a href="/disciplinaprofessor"><small>Ainda Precisamos De Alguns Dados Professor</small></a></h4>
                
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>