
<?php
        $foto;
        if(isset($this->view->foto_perfil)){
            $foto = $this->view->foto_perfil[0]['nome_foto'];
        }
        else
        {
            $foto = '';
        }
    
?>



<div class="container">
  <div class="row mt-0">
      <div class="col-12 mt-3">
     
      </div>
        
  </div>
  
<!---==============================================================================-->
<!---============================  TERCEIRO PASSO LOCAL  ============================-->
<!---==============================================================================-->
<div class="d-flex justify-content-center mt-5">
                <div class="card mt-0" style="width: 35rem;">
                    <div class="card-body">

                            <?php 
                                if($foto == ''){
                            ?>
                            <div class="d-flex justify-content-center">
                                <img class = "rounded-circle" src="/fotos_de_perfil/foto_perfil.jpg" style="width: 30%; right = 30%; " />
                            </div>
                            <?php  }else
                            
                                if($foto != ''){
                            ?>
                            <div class="d-flex justify-content-center" >
                                <img class = "rounded-circle" src="/fotos_de_perfil/<?= $foto ?>" style="width: 30%; right = 30%; "  />
                            </div>
                            <?php  }?>

                        <div class="row">
                        <div class="col">
                            <h2 class="text-center">Foto De Perfil</h2>
                        </div>
                        </div>

                        <div class="row">
                            
                            <div class="col-lg-12">
                                <form action="/guardar_foto" method="post" enctype = "multipart/form-data">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            
                                            <input type="FILE" name = "foto" class = "form-control">
                                        </div>
                                    </div>
                                    <div class = "row mt-2">
                                        <div class="col-lg-12">
                                            <button type="submit" class="btn btn-primary btn-block">Carregar</button>
                                        </div>    
                                    </div>
                                </form>
                            </div>
                        </div>
                        
                    

                    </div>
                </div>
            </div>

  <!---==============================================================================-->
        <!---============================  QUARTO PASSO LOCAL  ============================-->
    <!---==============================================================================-->
    
                 <div class="row mt-2">
                    <div class="col-12 m-auto">
                            <center>
                              <a href="/bemvindo_professor" style="width: 20rem;" type="submit" class="btn btn-primary btn-block mb-5">Seguinte</a> 
                            </center>
                                         
                    </div>
                  </div>


                  </form>

</div>