</br>
    </br>
    </br>
    </br>
<div class="container mt-5">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 30rem;">
      <div class="card-body">

            <div class="d-flex justify-content-center">
          		<img src="/img/teach.png" />
        	</div>

        <div class="row">
          <div class="col-lg-12">
            <h2 class="text-center">Bem Vindo</h2>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-12">
            
            <form action="/autenticar" method="post">
            <div class="d-flex justify-content-center">
                <img src="/img/bemvindo.png" alt="">
        	</div>
          <input type="hidden" value="<?= $_SESSION['email'] ?>">
          <input type="hidden" value="<?= $_SESSION['senha'] ?>">

                <button class = "btn btn-primary text-center">Ir para o Início</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>