<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
  <div class = "m-auto">
      <img src="/img/teacher_mim_br.png" />
  </div>

</nav>

<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card mt-5" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/teach.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2 class="text-center">Cadastro realizado com sucesso</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/perfil_aluno" class="btn btn-primary btn-block">Clique aqui para criar o teu perfil!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  