
<?= session_start() ?>
</br>
    </br>
    </br>
    </br>
    <div class = "modalalert">
			<center>
			<div class="row dentromodal">
				<div class="col-12">
				<div class="row">
						<div class="col-12 m-auto">
							<img id = "imagem_erro" src="assets/img/erro_conexao.png" alt="" style="width: 3rem;">
						</div>
					</div>
				<div class="row">
						<div class="col-12 m-auto">
							<h4 class = "text-center" id = "mensagem_erro">ERRO NA CONEXÃO</h4>
						</div>
					</div>
					<div class="row">
						<div class="col-12 m-auto">
							<button onclick = "fechar_modal()" class = "btn btn-light border border-primary">Fechar</button>
						</div>
					</div>
				</div>
			</div>
			</center>
			</div>
<div class="container mt-5">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 30rem;">
      <div class="card-body">

            <div class="d-flex justify-content-center">
          		<img src="/img/teach.png" style="width: 6rem;" />
        	</div>

        <div class="row">
          <div class="col-lg-12">
            <h5 class="text-center"><small>Enviamos um codigo de confirmação no teu email</small></h5>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-12">
         
                <div class="d-flex justify-content-center">
                    <input id = "codigo_enviado" type="text" class = "form-control mb-4 text-center">
                </div>
                <input type="hidden"  id ="email" value="<?= $_SESSION['email'] ?>">
                <input type="hidden"id ="senha" value="<?= $_SESSION['senha'] ?>">
                <input type="hidden" id ="nome" value="<?= $_SESSION['nome'] ?>">
                <input type="hidden" id ="codigo" value="<?= $_SESSION['codigo'] ?>">
                <center>
                    <button onclick = "registrar_usuario()" style="width: 70%;" class = "btn btn-primary">Confirmar</button>
                </center>
            
          </div>
        </div>

      </div>
    </div>
  </div>
</div>