
<div class="container">
    <div class="row mt-5">
        <div class="col-lg-4 m-auto  m-4">
            <div class="card mb-3">
            <div class = "card-header">
                    <h4>Professor</h4>
            </div>
            <div class="card-body">

                <div class="d-flex justify-content-center">
                    <img src="/img/professor.png" />
                </div>
            </div>
            <div class="card-footer">
                    <a href="/perfil_professor" class="btn btn-primary btn-block">Criar Perfil</a>
            </div>
            </div>
        </div>

        <div class="col-lg-4 m-auto m-4">
        <div class="card mb-3">
          <div class = "card-header">
                <h4>Aluno</h4>
          </div>
          <div class="card-body">

              <div class="d-flex justify-content-center">
                  <img src="/img/aluno.png" />
              </div>
          </div>
          <div class="card-footer">
                <a href="/perfil_aluno" class="btn btn-primary btn-block">Criar Perfil</a>
          </div>
          </div>
        </div>
    </div>
</div>