

<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 30rem;">
      <div class="card-body">

          <div class="d-flex justify-content-center">
          		<img src="/img/teach.png" style="width: 6rem;"/>
        	</div>
          
          <div id = "corpo">
        <div class="row">
          <div class="col">
            <h2 class="text-center">Criar Conta</h2>
          </div>
        </div>
     
     
            <h5 class = "text-center text-danger" id = "mensagem_erro_ins"></h5>
 
        <div class="row" >
       
          <div class="col">
              <div class="form-group">
                <input id = "nome" type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input id = "email" type="email" value="<?= $this->view->usuario['email'] ?>" name="email" class="form-control" placeholder="E-mail">
              </div>
              

              <div class="form-group">
                <input id = "pass" type="password" value="<?= $this->view->usuario['senha'] ?>" name="senha" class="form-control" placeholder="Senha">
              </div>
              <div class="form-group">
                <input id = "confirma_pass" type="password" value="<?= $this->view->usuario['senha'] ?>" name="senha" class="form-control" placeholder="Confirmar Senha">
              </div>
              

              <div class="row">
                <div class="col-8 m-auto">
			
                  <?php if($this->view->erroCadastro){ ?>
                    <small class = "form-text text-danger">Erro ao tentar cadastra</small>
                  <?php }?>
                  
                    <button onclick = "registrar()" type="submit" class="btn btn-primary btn-block">Inscrever-se</button>                  
                </div>
              </div>
              <div class="mt-2 mb-4">
                <small class="form-text text-center">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade
                </small>
              </div>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>