

<div id="loading">Loading&#8230;</div>

    <div class="row">
    <div id="inbox" class="col-lg-3 col-md-8 column column  ">
        <p class="title">Conversas</p>
        <input type="text" maxlength="15" name="username" class="searchField" onkeyup="search()" placeholder="Pesquisar utilizador" />
        <div id="searchContainer"></div>
        <div class="container"></div>
    </div>

    <div id="chat" class="col-lg-6 col-md-8 column"></div>

    <div id="profile" class="col-3 column d-none d-lg-block">
        
        <div class="container"></div>
        <div class="menu">
            
            <button onclick="logout()">Sair</button>
        </div>
    </div>
    </div>

    <script src="asset/js/script.js"></script>