
  <div class = "modalalert">
			<center>
			<div class="row dentromodal">
				<div class="col-12">
				<div class="row">
						<div class="col-12 m-auto">
							<img src="assets/img/erro_conexao.png" alt="" style="width: 3rem;">
						</div>
					</div>
				<div class="row">
						<div class="col-12 m-auto">
							<h4 id = "mensagem_modal" class = "text-center">DESEJAS APAGAR</h4>
						</div>
					</div>
					<div id = "confirmar" class="row">
					
					</div>
				</div>
			</div>
			</center>
			</div>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
      <?php if($_SESSION['perfil'] == '2'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline_professor"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/professor"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Publico"></a></li>
          <li><a href="/tarefa_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_enviadas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/alunos"><img id = "aluno" style="width: 1.7rem;" src="assets/img/menu/aluno/0.png" alt="Publico"></a></li>
          <li><a href="/turma"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public2.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php } else?>
      <?php if($_SESSION['perfil'] == '1'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <?php 
        

          $respondidas = 0;
          $tarefa = 0;
          if($this->view->tarefa_novo['quantidade'] > 9){
            $tarefa = 10;
          }else
          {
            $tarefa = $this->view->tarefa_novo['quantidade'];
          }
           //=======================================================
          if($this->view->respondidas['quantidade'] > 9){
            $respondidas = 10;
          }else
          {
            $respondidas = $this->view->respondidas['quantidade'];
          }
           //=======================================================
           if($this->view->notificacao_novo['quantidade'] > 9){
            $notificacao = 10;
          }else
          {
            $notificacao = $this->view->notificacao_novo['quantidade'];
          }
          

 ?>
         <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="#"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/<?= $notificacao ?>.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/<?= $tarefa ?>.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/<?= $respondidas ?>.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public2.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php }?>

    </div>
  </header><!-- End Header -->

 

  <main>
    <section id="contact" class="contact">
    <div class="row" id = "top">
        <div class="col-lg-5 d-none d-lg-block" id = "fixo">
             
        <div class="row">
        <div class="col-lg-12">
          <div class="row mt-0">
            <div class="col-12">
                <div class="col-lg-12" >
                  <div>
                 
                  <center>
                  <h5><b>Minhas postagens</b></h5>
                  </center>
                  <?php 
                  $cont = 0;
                  foreach($this->view->minhas_postagem as $key => $valor){ 
                
                    ?>
                          <div class="row mb-3">
                            <div class="col-12">
                              <div class="card">
                                <div class="card-header">
                                  <div class="row">
                                    <div class="col-2">
                                    <?php if($valor['id_usuario'] == $_SESSION['id']){  ?>
                                      <a href="/aluno"><img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?=  $valor['nome_foto']?>" style="width: 3rem; height: 3rem; object-fit: cover;" /></a>
                                    <?php  }else ?>
                                    <?php if($valor['id_usuario'] != $_SESSION['id']){  ?>
                                      <a href="/professor?id_professor=<?= $valor['id_usuario'] ?>"><img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?=  $valor['nome_foto']?>" style="width: 3rem; height: 3rem; object-fit: cover;" /></a>
                                    <?php  }else ?>
                                    </div>
                                    <div class="col-7">
                                      <h5 ><?= $valor['nome'] ?> </br> <small> <?=  $valor['data']?></small> </h5>
                                    </div>
                                    <?php if($valor['id_usuario'] == $_SESSION['id']){  ?>
                                    <div class="col-3">
                                      <div class="row">
                                         
                                         
                                      </div>
                                    </div>
                                    <?php  }?>
                                    
                                  </div>
                                </div>
                                 <div class="container mb-0">
                                 <h5><?= $valor['titulo'] ?></h5>
                                 </div>
                                  <div style="margin: 10px;">
                                    <div class="card-header">
                                      <p style="width: 100%;">
                                        <?= $valor['tweet'] ?>
                                      </p>
                                     
                                    </div>
                                  </div>
                                  <?php if($valor['imagem_carregada'] != 'indefinido'){  ?>
                                      <img class = "card-img-top" src="/imagem_carregada/<?=  $valor['imagem_carregada']?>" />
                                     
                                  <?php }?>
                                  <?php if($valor['pdf'] != 'indefinido'){  ?>
                                    <img class = "card-img-top" src="/imagem_carregada/imagempdf.jpg" />
                                      <div style = " background: #ffaa0d;">
                                       <h5 class = "mx-2"><small><?= $valor['pdf_original'] ?></small></h5>
                                       <p class = "mx-3 mt-0"><small><?= $valor['pdf_descricao'] ?></small></p>
                                       <div>
                                       <a href="./ficheiro_pdf/<?= $valor['pdf'] ?>" class = "btn btn-light mr-2"   style="width: 95%; margin: 10px; margin-top: -10px; " >
                                           <b class = "text-primary">Baixar PDF</b>     
                                       </a>
                                       </div>
                                      </div>
                                      <?php }?>
                                  <?php if($valor['id_usuario'] != $_SESSION['id']){  ?>
                                    <div class="row">
                                  <?php if ($valor['estado_like'] == 0) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "like(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)"  src="assets/img/coracao1.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <?php if ($valor['estado_like'] == 1) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "remover_like(<?= $valor['id'] ?>)"  src="assets/img/coracao.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  
                                  <?php }?>

                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "salvar(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                <p style="width: 90%; margin: 0px; " id = "numeroSalvar<?= $valor['id'] ?>"><?= $this->view->num_arquivado[$cont] ?> <img  src="assets/img/salve.png" style="width: 1.4rem;" /></p>  
                                                
                                            </button>
                                      </div>
                                  </div>
                                  
                              </div> 
                              <div class="row">
                                  
                                  <div class="col-12">
                                      <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                       <a href="/comentarios?id_postagem=<?= $valor['id'] ?>">
                                          <button class = "btn btn-light border border-primary" style="width: 95%; margin: 10px; " type="submit"  >
                                            <img style="width: 1.5rem;" class="text-center" src="assets/img/responder2.png" alt="">
                                          </button>
                                       </a>
                                        
                                          
                                        
                                       
                                      </div>
                                  </div>
                              </div>
                                <?php  }?>
                                
                              <div class="row">
                                  
                                    <div class="col-12">
                                        <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                        <a href="/comentarios?id=<?= $valor['id'] ?>">
                                          <button class = "btn btn-light border border-primary" style="width: 95%; margin: 10px; " type="submit"  >
                                            <img style="width: 1.5rem;" class="text-center" src="assets/img/responder2.png" alt="">
                                          </button>
                                        </a>
                                         
                                        </div>
                                    </div>
                                </div>
                              <?php  ?>
                              </div>
                            </div>
                    </div>
                <?php $cont++;  }?>
           <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                  </div>
                </div>
           

        </div>
      </div>  
  <!-- ======= FIM DA AREA ONDE VC VE TODAS AS POSTAGEM ======= -->


  </div>
  <!-- ======= FIM DA AREA DOS POST ======= -->


</div>
        </div>


            <div class="col-lg-2 mr-4  d-none d-sm-block" id = "principal"></div>

<div class="col-lg-6 m-auto col-md-12 col-sm-12" >
  

    <!-- ======= AREA ONDE PODES VER TODAS AS POSTAGEM ======= -->

    <div class="row">
        <div class="col-lg-12">
          <div class="row mt-0">
            <div class="col-12">
                <div class="col-lg-12" >
                  <div>
                  <center>
                  <h5><b>Todas as postagem</b></h5>
                  </center>
                  <?php if($_SESSION['limite_p'] != 0){?>
                    <div class ="row mb-3">
                        <div class="col-12">
                          <a href="/vermenus_p">
                            <button class = "btn btn-light border-primary" style = "width: 100%"> Ver Anterior </button>
                          </a>
                        </div>
                    </div>
                  <?php }?>
                  <?php
                  if(count($this->view->tweet) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="" >
                        <p><small>Ainda não tens nenhuma publicação!</small></p>
                        </center>
                       
                    <?php } else {
                          $cont = 0;
                          foreach($this->view->tweet as $key => $valor){ 
                            if($cont >= $_SESSION['limite_p'] && $cont < $_SESSION['limite_p'] + 7){
                            ?>
                          <div class="row mb-3" id = "postagem<?= $valor['id'] ?>">
                            <div class="col-12">
                              <div class="card">
                                <div class="card-header">
                                  <div class="row">
                                    <div class="col-2">
                                    
                                      <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?=  $valor['nome_foto']?>" style="width: 3rem; height: 3rem; object-fit: cover;" />
                                   
                                   

                                    </div>
                                    <div class="col-7">
                                      <h5 ><?= $valor['nome'] ?> </br> <small> <?=  $valor['data']?></small> </h5>
                                    </div>
                                    <?php if($valor['id_usuario'] == $_SESSION['id']){  ?>
                                    <div class="col-3">
                                      <div class="row">
                                          <div class="col-2">
                                              <img onclick = "apagar_modal(<?= $valor['id'] ?>)"  src="assets/img/delete.png" style="width: 1rem;" />
                                          </div>
                                          <div class="col-2">
                                              <a onclick = "editar(<?= $valor['id'] ?>,'<?= $valor['tweet'] ?>')"><img  src="assets/img/edit.png" style="width: 1rem;" /></a>
                                          </div>
                                         
                                      </div>
                                    </div>
                                    <?php  }?>
                                    
                                  </div>
                                </div>
                                 <div class="container mb-0">
                                 <h5><b><?= $valor['titulo'] ?></b></h5>
                                 </div>
                                  <div>
                                    <div id = "post_<?= $valor['id'] ?>">
                                      <p class = "ml-3">
                                        <?= $valor['tweet'] ?>
                                      </p>
                                     
                                    </div>
                                  </div>
                                  <?php if($valor['imagem_carregada'] != 'indefinido'){  ?>
                                      <img class = "card-img-top" src="/imagem_carregada/<?=  $valor['imagem_carregada']?>" />
                                     
                                  <?php }?>

                                  <?php if($valor['pdf'] != 'indefinido'){ 
                                    if($_SESSION['tema'] == 'layout'){
                                    ?>
                                    <img class = "card-img-top" src="/imagem_carregada/imagempdf.jpg" />
                                      <div style = " background: #000000;">
                                       <h5 class = "mx-2"><small><?= $valor['pdf_original'] ?></small></h5>
                                       <p class = "mx-3 mt-0"><small><?= $valor['pdf_descricao'] ?></small></p>
                                       <div>
                                       <a href="./ficheiro_pdf/<?= $valor['pdf'] ?>" class = "btn btn-light mr-2"   style="width: 95%; margin: 10px; margin-top: -10px; " >
                                           <b class = "text-primary">Baixar PDF</b>     
                                       </a>
                                       </div>
                                      </div>
                                      <?php }else{?>
                                        <img class = "card-img-top" src="/imagem_carregada/imagempdf.jpg" />
                                        <div style = " background: #ffaa0d;">
                                       <h5 class = "mx-2"><small><?= $valor['pdf_original'] ?></small></h5>
                                       <p class = "mx-3 mt-0"><small><?= $valor['pdf_descricao'] ?></small></p>
                                       <div>
                                       <a href="./ficheiro_pdf/<?= $valor['pdf'] ?>" class = "btn btn-light mr-2"   style="width: 95%; margin: 10px; margin-top: -10px; " >
                                           <b class = "text-primary">Baixar PDF</b>     
                                       </a>
                                       </div>
                                      </div>
                                      <?php }}?>
                                  <?php if($valor['id_usuario'] != $_SESSION['id']){  ?>
                                    <div class="row">
                                  <?php if ($valor['estado_like'] == 0) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "like(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)"  src="assets/img/coracao1.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <?php if ($valor['estado_like'] == 1) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "remover_like(<?= $valor['id'] ?>)"  src="assets/img/coracao.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  
                                  <?php }?>

                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "salvar(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                <p style="width: 90%; margin: 0px; " id = "numeroSalvar<?= $valor['id'] ?>"><?= $this->view->num_arquivado[$cont] ?> <img  src="assets/img/salve.png" style="width: 1.4rem;" /></p>  
                                                
                                            </button>
                                      </div>
                                  </div>
                                  
                              </div> 
                              <div class="row">
                                  
                                  <div class="col-12">
                                      <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                       <a href="/comentarios?id=<?= $valor['id'] ?>">
                                          <button class = "btn btn-light border border-primary" style="width: 95%; margin: 10px; " type="submit"  >
                                            <img style="width: 1.5rem;" class="text-center" src="assets/img/responder2.png" alt="">
                                          </button>
                                        </a>
                                        
                                          
                                        
                                       
                                      </div>
                                  </div>
                              </div>
                                <?php  } else{?>
                                <div class="row">
                                  
                                <?php if ($valor['estado_like'] == 0) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "like(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)"  src="assets/img/coracao1.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <?php if ($valor['estado_like'] == 1) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "remover_like(<?= $valor['id'] ?>)"  src="assets/img/coracao.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "salvar(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                <p style="width: 90%; margin: 0px; " id = "numeroSalvar<?= $valor['id'] ?>"><?= $this->view->num_arquivado[$cont] ?> <img  src="assets/img/salve.png" style="width: 1.4rem;" /></p>  
                                                
                                            </button>
                                      </div>
                                  </div>
                                  
                              </div> 
                              <div class="row">
                                  
                                    <div class="col-12">
                                        <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                        <a href="/comentarios?id=<?= $valor['id'] ?>">
                                          <button class = "btn btn-light border border-primary" style="width: 95%; margin: 10px; " type="submit"  >
                                            <img style="width: 1.5rem;" class="text-center" src="assets/img/responder2.png" alt="">
                                          </button>
                                        </a>
                                          
                                            
                                          
                                         
                                        </div>
                                    </div>
                                </div>
                              <?php  }?>
                              </div>
                            </div>
                    </div>
                    <?php }$cont++; }}?>
                    </div>
                    <?php if(count($this->view->tweet) > 10){
                      
                      ?>
                      <div class ="row">
                          <div class="col-12">
                            <a href="/vermais_p">
                              <button class = "btn btn-light border-primary" style = "width: 100%"> Ver mais </button>
                            </a>
                          </div>
                      </div>
                    <?php }?>
           <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                  </div>
                </div>
           

        </div>
      </div>  
  <!-- ======= FIM DA AREA ONDE VC VE TODAS AS POSTAGEM ======= -->


  </div>
  <!-- ======= FIM DA AREA DOS POST ======= -->


</div>

</div>
            </div>
           
         
    </section>

        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

    

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
