


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      <?php if($_SESSION['perfil'] == '2'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline_professor"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/professor"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Publico"></a></li>
          <li><a href="/tarefa_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_enviadas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/alunos"><img id = "aluno" style="width: 1.7rem;" src="assets/img/menu/aluno/0.png" alt="Publico"></a></li>
          <li><a href="/turma"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php } else?>
      <?php if($_SESSION['perfil'] == '1'){ 
        $tarefa = 0;
        $notificacao = 0;
        if($this->view->tarefa_novo['quantidade'] > 9){
          $tarefa = 10;
        }else
        {
          $tarefa = $this->view->tarefa_novo['quantidade'];
        }
         //=======================================================
         if($this->view->notificacao_novo['quantidade'] > 9){
          $notificacao = 10;
        }else
        {
          $notificacao = $this->view->notificacao_novo['quantidade'];
        }
        ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="#"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img style="width: 1.7rem;" src="assets/img/menu/notificacao/<?= $notificacao ?>.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img style="width: 1.7rem;" src="assets/img/menu/Tarefa/<?= $tarefa ?>.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas"><img style="width: 1.7rem;" src="assets/img/menu/duvida/<?= $respondidas ?>.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php }?>
      

    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
      
      <div class="row">

        <div class="col-lg-5 col-md-12 col-sm-12 m-auto">
            
                  <div class="row mt-0">
                  
                    <div class="col-12">
                        <div class="col-lg-12" data-aos="fade-up" >
                          <div>
		                      <!-- ======= CARD DE POSTAGEM ======= -->
		  										<div class="row">
                <div class="col-lg-12" data-aos="fade-up" >
                <div class="row">
                    <div class="col-6">
                    <div class="card mb-3  border border-primary">
                      <div class="row" >
                        <div class="col-12">
                          <div class=" align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                            <a href="/alunos">
                                    <div class="row">
                                      <div class="col-4">
                                      <img src="/assets/img/sobre_pessoal/pedido.png" style="width: 3rem;" />
                                      </div>
                                      <div class="col-8">
                                        <p></br>Pedidos</p>  
                                      </div>
                                    </div>
                                  </a>
                          </div>
                        </div>
                      </div>
                    </div>
                    </div>
                    <div class="col-6">
                    <div class="card mb-3  border">
                        <div class="row" >
                          <div class="col-12">
                            <div class=" align-items-stretch" data-aos-delay="100">
                                    <a href="/listar_aluno">
                                      <div class="row">
                                        <div class="col-4">
                                          <img src="/assets/img/sobre_pessoal/alunos.png" style="width: 3rem;" />
                                        </div>
                                        <div class="col-8">
                                          <p></br>Listar Meus Alunos</p>  
                                        </div>
                                      </div>
                                    </a>
                                  
                            </div>
                          </div>
                          
                        </div>

                      </div>
                    </div>
                </div>
                         
                                
                            <?php
                            if (empty($this->view->pedidos)){?>
                             <p class = "text-center mt-5"><img style="width: 10rem;" src="assets/img/vazio.png" alt="Publico"></p> 
                              <?php }else{ foreach($this->view->pedidos as $key => $valor){  ?>
                            
                            
                            <div class="row mb-3" id = "aluno<?= $valor['id_relacao'] ?>">
                                    <div class="col-12">

                                      <div class="card">
                                       
                                        <div class="card-body">
                                            <div class="row">
                                                
                                                <div class="col-4 text-center">
                                                <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>" style="width: 8rem;" />
                                                
                                              </div>

                                                <div class="col-8">
                                                    <h4 ><?= $valor['nome'] ?></h4>
                                                    <p ><img style="width: 1.3rem;" src="assets/img/local.png" alt="Publico"> <?= $valor['cidade'] ?>/<?= $valor['municipio'] ?>/<?= $valor['bairro'] ?></p>
                                                    <p ><img style="width: 1.3rem;" src="assets/img/escola.png" alt="Publico"> <?= $valor['curso'] ?></p>
                                                    <div class="row">
                                                  
                                                    <div class="col-6">
                                                        <a onclick = "aceitar_pedido(<?= $valor['id_relacao'] ?>,<?= $valor['id'] ?>)" style = "width: 100%;" class = "btn btn-primary">Aceitar</a>
                                                    </div>

                                                    <div class="col-6">
                                                        <a href="/aluno?id_aluno=<?= $valor['id'] ?>"><button style = "width: 100%;" class = "btn btn-info">Ver perfil</a></a>
                                                    </div>
                                                   
                                                </div>
                                                </div>
                                                
                                                
                                            </div>

                                        </div>
                                    </div>
                                    
                                 </div>

                          </div>
                          <?php }} ?>
                        </div>
                    </div>
                  </div>

                 
            </div>
         </div>
            
          <!-- ======= FIM DA AREA DOS POST ======= -->

        

          

        </div>

      </div>
   
    </section>
        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

   

  </main><!-- End #main -->
  <div class="col-lg-8">
  <!-- Modal -->

  

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
