


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      <?php if($_SESSION['perfil'] == '1'){  ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas"><img style="width: 1.7rem;" src="assets/img/duvida3.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php }?>
      
    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
      
      <div class="row" id = "top">

<div class="col-lg-6 col-md-12 col-sm-12 m-auto">

<div class="row">
  <div class="col-lg-12" data-aos="fade-up">
    <div class="row mt-0">
      <div class="col-12">
      
          <div class="col-lg-12" data-aos="fade-up" >
            <div>
            <div class="row mb-3">
              
            <div class="col-12 m-auto">
                <div class="row">
                <div class="col-6">
              <div class="card  border border-primary">
                  <div class="row m-3" >
                    <div class="col-12">
                      <div class=" align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                              <a href="/duvidas_respondidas">
                                <div class="row">
                                <div class="col-4">
                                    <img src="/assets/img/resposta/enviada.png" style="width: 2rem;" />
                                  </div>
                                  <div class="col-lg-8 col-md-8 d-none d-md-block col-sm-12">
                                    <p >Respondidas</p>  
                                  </div>
                                </div>
                              </a>  
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-6">
              <div class="card">
                  <div class="row m-3" >
                    <div class="col-12">
                      <div class=" align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                              <a href="/duvida">
                                <div class="row">
                                <div class="col-4">
                                    <img src="/assets/img/resposta/respondida.png" style="width: 2rem;" />
                                  </div>
                                  <div class="col-lg-8 col-md-8 d-none d-md-block col-sm-12">
                                    <p >Enviadas</p>  
                                  </div>
                                </div>
                              </a>  
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                </div>
              </div>
              
              </div>
                  <!-- ======= CARD DE POSTAGEM ======= -->
                  <?php
                  if(count($this->view->respostas) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="" style="margin-top: 20%;">
                        <p><small>Ainda não recebeste nenhuma resposta para listar!</small></p>
                        </center>
                       
                    <?php } else {
                       foreach($this->view->respostas as $key => $valor){?>
                          <div class="row mb-2" id = "resposta<?= $valor['id_duvida_respondida'] ?>">
                            <div class="col-12">
                              <div class="card">

                          <div class="row m-2">
                            <div class="col-12">
                              <div>
                              <div class="card-header">
                                  <div class="row">
                                    <div class="col-2">
                                    <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $_SESSION['foto_perfil']?>" style="width: 2rem;" />
                                    </div>
                                    <div class="col-10">
                                      <h5 ><?= $_SESSION['nome']?> / <small class = "text-success">Pergunta Feita</small> </h5>
                                    </div>
                                  </div>
                                </div>
                                
                                  <h5 class = "ml-2 text-red"><b><?= $valor['titulo'] ?></b></h5>
                               
                                
                                       
                                
                                  <div style="margin: 10px;">
                                    <div class="card-header">
                                      <p style="width: 100%;">
                                      <?= $valor['duvida'] ?>
                                      </p>
                                    </div>
                                  </div>
                                  

                                
                              </div>
                            </div>
                          </div>
                          <div class="row m-2">
                            <div class="col-12">
                              <div>
                                
                                        
                                    <div class="card-header">
                                    <div class="row">
                                    <div class="col-2">
                                    <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto']?>" style="width: 2.5rem;" />
                                    </div>
                                    <div class="col-10">

                                    <h5 ><?= $valor['nome']?> / <small class = "text-success">Resposta Enviada</small> </h5>
                                      
                                    </div>
                                    
                                  
                                   
                                    
                                    
                                  </div>
                                </div>
                                
                                  <div style="margin: 10px;">
                                    <div class="card-header">
                                      <p style="width: 100%;">
                                        <?= $valor['resposta'] ?>
                                      </p>
                                    </div>
                                  </div>
                                  
                                <div class="row">
                                  
                                    <div class="col-12">
                                        <div class = "text-center">

                                            <a onclick = "iliminar_resposta(<?= $valor['id_duvida_respondida'] ?>)" class = "btn btn-danger" style="width: 95%; margin: 10px; ">
                                              <img style="width: 1rem;" class="text-center" src="assets/img/erro.png" alt="">
                                            </a>
                                          
                                        </div>
                                    </div>
                                    
                                   
                                </div>
                                <?php if($valor['avaliacao'] == 0){  ?>
                                <div class="border border-primary m-3" id = "estrelas<?= $valor['id_duvida_respondida'] ?>">
                               
                                        <div class="estrela">
                                            <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                            <label class = "ml-3 mr-1" for="estrela_um" ><img onclick ="clicke(<?= $valor['id_duvida_respondida'] ?>,1)" id = "estrela1<?= $valor['id_duvida_respondida'] ?>" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                            <input class = "ml-3 mr-1 estrela<?= $valor['id_duvida_respondida'] ?>" type="radio" id = "estrela_um" name = "estrela<?= $valor['id_duvida_respondida'] ?>" value = "1">
                                            
                                            <label class = "mr-1" for="estrela_dois" ><img onclick ="clicke(<?= $valor['id_duvida_respondida'] ?>,2)" id = "estrela2<?= $valor['id_duvida_respondida'] ?>" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                            <input class = "mr-1 estrela<?= $valor['id_duvida_respondida'] ?>" type="radio" id = "estrela_dois" name = "estrela<?= $valor['id_duvida_respondida'] ?>" value = "2">

                                            <label class = "mr-1" for="estrela_tres" ><img onclick ="clicke(<?= $valor['id_duvida_respondida'] ?>,3)" id = "estrela3<?= $valor['id_duvida_respondida'] ?>" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                            <input class = "mr-1 estrela<?= $valor['id_duvida_respondida'] ?>" type="radio" id = "estrela_tres" name = "estrela<?= $valor['id_duvida_respondida'] ?>" value = "3">

                                            <label class = "mr-1" for="estrela_quatro" ><img onclick ="clicke(<?= $valor['id_duvida_respondida'] ?>,4)" id = "estrela4<?= $valor['id_duvida_respondida'] ?>" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                            <input class = "mr-1 estrela<?= $valor['id_duvida_respondida'] ?>" type="radio" id = "estrela_quatro" name = "estrela<?= $valor['id_duvida_respondida'] ?>" value = "4">

                                            <label class = "mr-2" for="estrela_cinco" ><img onclick ="clicke(<?= $valor['id_duvida_respondida'] ?>,5)" id = "estrela5<?= $valor['id_duvida_respondida'] ?>" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                            <input class = "mr-2 estrela<?= $valor['id_duvida_respondida'] ?>"type="radio" id = "estrela_cinco" name = "estrela<?= $valor['id_duvida_respondida'] ?>" value = "5">
                                            
                                            <input onclick ="avaliar(<?= $valor['id'] ?>,<?= $valor['id_duvida_respondida'] ?>)" class = "btn btn-info  m-1" type="submit" value = "Avaliar">
                                            <input onclick ="depois(<?= $valor['id_duvida_respondida'] ?>)" class = "btn btn-info  " type="submit" value = "Agora Não">

                                        </div>
                                </div>
                                <?php } ?>
                              </div>
                            </div>
                          </div>
                              </div>
                              
                            </div>
                            
                          </div>

                          
                <?php  }}?>
                  </div>
                </div>
      </div>  
  </div>
</div>

</div>
            </div>
          </div>
        </div>
      </div>
    </div>
      
    </section>

        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

    

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
