

<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 30rem;">
      <div class="card-body">

          <div class="d-flex justify-content-center">
          		<img src="/img/teach.png" style="width: 6rem;"/>
        	</div>
          
          <div id = "corpo">
        <div class="row">
          <div class="col">
            <h2 class="text-center">Apagar Conta</h2>
          </div>
        </div>
     
     
            <h5 class = "text-center text-danger" id = "mensagem_erro_ins"></h5>
 
        <div class="row" >
       
          <div class="col">
             
              <div class="form-group">
                <input id = "pass" type="password" value="" name="senha" class="form-control" placeholder="Confirmar Senha">
              </div>
              

              <div class="row">
                <div class="col-8 m-auto">
			
                  
                    <button onclick = "iliminar_conta()" type="submit" class="btn btn-danger btn-block">APAGAR</button>                  
                </div>
              </div>
              <div class="mt-2 mb-4">
                <small class="form-text text-center text-info">
                  Aviso: Ao apagares a tua conta não perderas acesso a todos os dados como: Imagens, Respostas, Documentos, Conversas etc. E não será possível recuperar, tens a certeza que desejas apagar a tua conta?
                </small>
              </div>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>