


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor2.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas" id = "duvida"><img style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
     
      
    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
      
      <div class="row" id = "top">

<div class="col-lg-6 col-md-12 col-sm-12 m-auto">
            <div class="row">
                <div class="col-lg-12" data-aos="fade-up" >
                  <div class="row mt-0">
                    <div class="col-12">
                        <div class="col-lg-12" data-aos="fade-up" >
                          <div>
		                      <!-- ======= CARD DE POSTAGEM ======= -->
		  										
                         
                                  <div class="row mb-3">
                                    <div class="col-12">

                                      <div class="card">
                                        
                                        <div class="card-body">
                                        <form action="pesquisar_professor" method="get">
                                            <div class="row">
                                               
                                                   <div class="col-lg-10 mr-0">
                                                        <input name = "procurado" class = "form-control" type="text">
                                                    </div>
                                                    <div class="col-2 ml-0">
                                                        <button class = "btn btn-primary"><img style="width: 1rem;" src="assets/img/pesquisar.png" alt="Publico"></button>
                                                    </div>
                                               
                                            </div>
                                         </form>
                                        </div>
                                       
                                    </div>
                                 </div>


                                 
                                
                            </div>
                            <?php
                  if(count($this->view->lista_prof) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="" style="margin-top: 20%;">
                        <p><small>Ainda não tens nenhuma professor para listar!</small></p>
                        </center>
                       
                    <?php } else {
                            
                            foreach($this->view->lista_prof as $key => $valor){  ?>
                            <div class="row mb-3">
                                    <div class="col-12">

                                      <div class="card">
                                       
                                        
                                              <div class="row m-2">
                                                
                                                <div class="col-2">
                                                  <a href="/professor?id_professor=<?= $valor['id'] ?>">
                                                  <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>" style="width: 3rem; height: 3rem; object-fit: cover;" />
                                                
                                                  </a>
                                                 </div>

                                                <div class="col-7">
                                                    <h5><small><?= $valor['nome'] ?></small></h5>
                                                </div>

                                               
                                                <div class="col-3 ml-0">
                                                    <button onclick = "enviar_duvida(<?= $valor['id'] ?>);" style = "width: 100%;" class = "btn btn-info">Dúvida</button>
                                                </div>
                                                <h5 class = "text-success ml-1" id = "texto_<?= $valor['id'] ?>"></h5>
                                              </div>

                                              <div class = "row">
                                                    <div class="col-12" id = "professor_<?= $valor['id'] ?>">

                                                    
                                                    </div>
                                              </div>
                                              
                                    </div>
                                   
                                 </div>

                        
                   <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                          </div>
                          <?php }} ?>
                        </div>
                    </div>
                  </div>

              
         </div>
            
          <!-- ======= FIM DA AREA DOS POST ======= -->

        

          

        </div>

      </div>
   
    </section>
        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

   

  </main><!-- End #main -->
  <div class="col-lg-8">
  <!-- Modal -->

  

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
