<div class = "modalalert">
			<center>
			<div class="row dentromodal">
				<div class="col-12">
				<div class="row">
						<div class="col-12 m-auto">
							<img src="assets/img/erro_conexao.png" alt="" style="width: 3rem;">
						</div>
					</div>
				<div class="row">
						<div class="col-12 m-auto">
							<h4 id = "mensagem_modal" class = "text-center">DESEJAS APAGAR</h4>
						</div>
					</div>
					<div id = "confirmar" class="row">
					
					</div>
				</div>
			</div>
			</center>
			</div>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">
    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
      <?php if($_SESSION['perfil'] == '2'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline_professor"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/professor"><img style="width: 1.7rem;" src="assets/img/perfil2.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Publico"></a></li>
          <li><a href="/tarefa_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_enviadas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/alunos"><img id = "aluno" style="width: 1.7rem;" src="assets/img/menu/aluno/0.png" alt="Publico"></a></li>
          <li><a href="/turma"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php } else?>
      <?php if($_SESSION['perfil'] == '1'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil2.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas" id = "duvida"><img style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php }?>

    </div>
  </header><!-- End Header -->

  

  <main>

  <section id="contact" class="contact">
      
        

      <div class="row" id = "top">
      
        <div class="col-lg-3 d-none d-lg-block" id = "fixo">
              <div class=" mb-3">
                <div class="row m-3" >
                  <div class="col-12">
                    <div class=" align-items-stretch"  data-aos-delay="100">
                        <b>SOBRE</b>
                          
                              <div class="row border border-primary">
                                <div class="col-4">
                                  <img src="/assets/img/sobre_pessoal/curso.png" style="width: 3rem;" />
                                </div>
                                <div class="col-8">
                                  <p style = "margin-top: 10%;"><?= $this->view->dados_pessoal[0]['escola'] ?></p>  
                                </div>
                              </div>
                            
                           
                              <div class="row border border-primary mt-3">
                                <div class="col-4">
                                  <img src="/assets/img/sobre_pessoal/escola.png" style="width: 3rem;" />
                                </div>
                                <div class="col-8">
                                  <p style = "margin-top: 10%;"><?= $this->view->dados_pessoal[0]['curso'] ?></p>  
                                </div>
                              </div>
                       
                              <div class="row border border-primary mt-3">
                                <div class="col-4">
                                  <img src="/assets/img/sobre_pessoal/local.png" style="width: 3rem;" />
                                </div>
                                <div class="col-8">
                                  <p style = "margin-top: 10%;"><?= $this->view->dados_pessoal[0]['cidade'] ?> - <?= $this->view->dados_pessoal[0]['municipio'] ?></p>  
                                </div>
                              </div>

                              <div class="row border border-primary mt-3">
                                <div class="col-4">
                                  <img src="/assets/img/sobre_pessoal/email.png" style="width: 3rem;" />
                                </div>
                                <div class="col-8">
                                  <p style = "margin-top: 10%;"><?= $this->view->dados_pessoal[0]['email'] ?></p>  
                                </div>
                              </div>

                              <div class="row border border-primary mt-3">
                                <div class="col-4">
                                  <img src="/assets/img/sobre_pessoal/numero_telefone.png" style="width: 3rem;" />
                                </div>
                                <div class="col-8">
                                  <p style = "margin-top: 10%;"><?= $this->view->dados_pessoal[0]['telefone'] ?></p>  
                                </div>
                              </div>

                              <div class="row border border-primary mt-3">
                                <div class="col-4">
                                  <img src="/assets/img/sobre_pessoal/aniversario.png" style="width: 3rem;" />
                                </div>
                                <div class="col-8">
                                  <p style = "margin-top: 10%;"><?= $this->view->dados_pessoal[0]['data_nasc'] ?></p>  
                                </div>
                              </div>

                    </div>
                  </div>
                  
                </div>

              </div>
              <div class="mb-3">
                <div class="row m-3" >
                  <div class="col-12">
                    <div class=" align-items-stretch" data-aos-delay="100">
                        <small style = "color: black;"><b>DISCIPLÍNA</b></small>
                        <?php  foreach($this->view->disciplina_lecionar as $key => $valor){ ?>
                        <div class="row border border-primary mt-3">
                          <div class="col-4">
                            <img src="/assets/img/sobre_pessoal/disciplina.png" style="width: 3rem;" />
                          </div>
                          <div class="col-8">
                            <p style = "margin-top: 10%;"><?= $valor['disciplina'] ?></p>  
                          </div>
                        </div>
                        <?php } ?>
                    </div>
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <div class="row m-3" >
                  <div class="col-12">
                    <div class=" align-items-stretch" data-aos-delay="100">
                        <small style = "color: black;"><b>DEFINIÇÃO</b></small>
                        <div class="row border border-primary mt-1">
                          <div class="col-3">
                            <img src="/assets/img/sobre_pessoal/def.png" style="width: 3rem;" />
                          </div>
                          <div class="col-6">
                            <p style = "margin-top: 10%;">Definição</p>  
                          </div>
                          <div class="col-3">
                            <img data-toggle="modal" data-target="#modalExemplo" src="assets/img/ir.png" alt="">
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>


            <div class="col-lg-1 d-none d-sm-block" id = "principal"></div>


<!-- =================================================================== -->
<!-- ======================= MENU DE PUBLICIDADE======================== -->
<!-- =================================================================== -->
<div class="col-lg-3 d-none d-lg-block" id = "fixoc">
<b>MEUS ALUNOS</b>
<?php
                  if(count($this->view->lista_alunos) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="" style="margin-top: 40%;">
                        <p><small>Ainda não tens nenhum aluno para listar!</small></p>
                        </center>
                       
                    <?php } else { foreach($this->view->lista_alunos as $key => $valor){  ?>
                      <div class="row">
                          <div class="col-2  mr-2">
                            <img class="rounded-circle border border-primary m-1" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>" style="width: 2.7rem; height: 2.7rem; object-fit: cover;" />
                          </div>
                        <div class="col-7">
                          <p style = "margin-top: 10%;" class = "d-none d-lg-block"><b><?= $valor['nome'] ?></b></p>  
                        </div>
                        <div class="col-2">    
                          <a href="/aluno?id_aluno=<?= $valor['id'] ?>">
                            <img src="/assets/img/sobre_pessoal/entrar.png" style="width: 2rem; margin-top: 60%;" />
                          </div>
                          </a>
                        </div>
                        <hr>
<?php }}?>
    
      
  </div>

  <!-- ======= AREA DOS POST ======= -->
  <!-- ======= AREA DOS POST ======= -->
  <!-- ======= AREA DOS POST ======= -->

<div class="col-lg-5 col-md-12 col-sm-12" id = "ficha_contrato">
          <!-- ======= PARTE DO CARD DA PUBLICAÇÃO ======= -->
         

          <div class="row m-3" >
                  <div class="col-12">
                    <div class=" align-items-stretch text-center"  data-aos-delay="100">
                    <?php if(!isset($_GET['id_professor'])){  ?>
                    <form action="/alterar_foto" method="POST" enctype="multipart/form-data" id="uploadPic">
                        <input onchange = "trocar_foto()" type='file' name="imagem" accept="image/x-png,image/jpeg" id="imgInp" hidden />
                        <div class="pictureContainer">
                            <label for="imgInp"><img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $this->view->minhas_foto?>" style="width: 7rem; height: 7rem; object-fit: cover; cursor:pointer;" /></label>
                        </div>
                        <small id = "confirma_foto"></small>
                    </form>
                    <br> <img data-toggle="modal" data-target="#modalExemplo" src="/assets/img/sobre_pessoal/def.png" style="width: 2rem; cursor:pointer;" />
                    <?php } ?>

                    <?php if(isset($_GET['id_professor'])){  ?>
                    
                      <label for="imgInp"><img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $this->view->minhas_foto?>" style="width: 7rem; height: 7rem; object-fit: cover;" /></label>
                    <br> <img data-toggle="modal" data-target="#sobre" src="/assets/img/sobre_pessoal/def.png" style="width: 2rem; cursor:pointer;" />
                    <?php } ?>   <br>    
                   <b><?=  $this->view->dados_pessoal[0]['nome'] ?></b>
                   <p><b>Alunos: <?= count($this->view->lista_alunos) ?> | Publicações: <?= count($this->view->minhas_postagem)  ?> | Turma: <?= count($this->view->turma)  ?></b></p>
                          
                          <div class="row">
                          
                              <div class="col-6 m-auto">
                              <?php 
                                                $valor['avaliacao'] = $this->view->minhas_avaliacao;
                                                if($valor['avaliacao'] < 1){  ?>
                                              
                                                        <div class="estrela">
                                                            <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                            <label for="estrela_um" ><img id = "estrela1" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                            
                                                            <label  for="estrela_dois" ><img  id = "estrela2" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                            <label  for="estrela_tres" ><img  id = "estrela3" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                            <label  for="estrela_quatro" ><img id = "estrela4" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                            <label  for="estrela_cinco" ><img id = "estrela5" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                            
                                                </div>
                                                <?php } ?>
                                                <?php if($valor['avaliacao'] >= 1 && $valor['avaliacao'] < 2){  ?>
                                              
                                              <div class="estrela">
                                                  <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                  <label for="estrela_um" ><img id = "estrela1" style="width: 2rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                  <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                  
                                                  <label  for="estrela_dois" ><img  id = "estrela2" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                  <label  for="estrela_tres" ><img  id = "estrela3" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                  <label  for="estrela_quatro" ><img id = "estrela4" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                  <label  for="estrela_cinco" ><img id = "estrela5" style="width: 2rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                  
                                      </div>
                                      <?php } ?>
                                      <?php if($valor['avaliacao'] >= 2 && $valor['avaliacao'] < 3){  ?>
                                              
                                                <div class="estrela">
                                                  <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                  <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                  <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                  
                                                  <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                  <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                  <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                  <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                  
                                                </div>
                                      <?php } ?>
                                      <?php if($valor['avaliacao'] >= 3 && $valor['avaliacao'] < 4){  ?>
                                              
                                              <div class="estrela">
                                                <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                
                                                <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                
                                              </div>
                                    <?php } ?>
                                    <?php if($valor['avaliacao'] >= 4 && $valor['avaliacao'] < 5){  ?>
                                              
                                              <div class="estrela">
                                                <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                
                                                <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                
                                              </div>
                                    <?php } ?>
                                    <?php if($valor['avaliacao'] >= 5 ){  ?>
                                              
                                              <div class="estrela">
                                                <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                
                                                <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                
                                              </div>
                                    <?php } ?>
                              </div>   
                                                   
                          </div>
                                                   
                                                
                                         
                    </div>
                  </div>
                </div>
          <!-- ======= FIM DO CARD DE PUBLICAÇÃO ======= -->
          <div class="row">
                <div class="col-lg-12" >
                  <div class="row mt-0">
                    <div class="col-12">
                        <div class="col-lg-12"  >
                          <div>
		                      <!-- ======= CARD DE POSTAGEM ======= -->
		  										
													
                          <div class="row mb-3">
                            <div class="col-12" >
                            <?php if(!isset($_GET['id_professor'])){  ?>
                            <form action="/tweet" method="post" enctype = "multipart/form-data">
                        <div class="row mb-3">
                            <div class="col-12">
                              <div class="card">
                                  
                                    <div class="card-body">
                                        <div class="row mb-2">
                                            <div class="col-4">
                                                <select id = "privacidade" class = "form-control" name="id_tipo">
                                                  <option value="2">Publica</option>
                                                  <option value="1">Privada</option>
                                                </select>
                                            </div>
                                            <div class="col-1 mr-4">
                                              <!-- <a href="./ficheiro_pdf/A_Ditadura_Da_Beleza_E_A_Revolucao_Das_Mulheres_-_Augusto_Cury.pdf.zip">Download</a> -->
                                              <input type='file' name="imagem" accept="image/x-png,image/jpeg" id="imagem" hidden />
                                              <div>
                                                  <label for="imagem"><img class=" border-primary" src="/assets/img/img.png" style="width: 2.5rem;" /></label>
                                              </div>
                                            </div>

                                            <div class="col-2">
                                              <!-- <a href="./ficheiro_pdf/A_Ditadura_Da_Beleza_E_A_Revolucao_Das_Mulheres_-_Augusto_Cury.pdf.zip">Download</a> -->
                                              <input type='file' name="pdf"  id="pdf" hidden />
                                              <div>
                                                  <label for="pdf"><img class=" border-primary" src="/assets/img/file.png" style="width: 2.5rem;" /></label>
                                              </div>
                                            </div>
                                           


                                          
                                        </div>
                                        
                                        
                                        <div class="row mb-2">
                                            <div class="col-12">
                                                <input id = "titulo" class = "form-control" name = "titulo" type="text" placeholder = "Título">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <textarea id = "postagem" class="form-control" name="tweet" rows="3" data-msg="Escreva alguma dúvida!" placeholder="Escreva aqui a tua dúvida"></textarea>

                                            </div>
                                        </div>
                                        <small><h5 id = "mensagem" class = "text-success text-center"></h5></small>
                                    </div>
                                 
                                   
                                <div class="row">
                               
                                    <div class="col-12">
                                        <div >
                                        
                                        <div class="text-center mb-2">
                                       
                                        <button style = " width: 50%; margin-top: -20px;" class = "btn btn-primary" type="submit">
                                          Carregar Publicação
                                        </button>
                                        </div>

                                         
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-7 m-auto">
                                    <?php if(isset($_GET['men'])){  ?>
                                        <small class = "text-danger">O teu conteúdo não foi publicado Tente novamente</small>
                                    <?php } ?>
                                    </div>
                                </div>
                              </div>
                            </div>
                      </div>
      </form>
      <?php }  ?>
                                       
                
                        
                   <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                          </div>
                        </div>
                    </div>
                  </div>

                </div>
              </div>  

            <!-- ======= AREA ONDE PODES VER TODAS AS POSTAGEM ======= -->

              <div class="row">
                <div class="col-lg-12" >
                  <div class="row">
                    <div class="col-12">
                        <div class="col-lg-12"  >
                          <div>
		                      <!-- ======= CARD DE POSTAGEM ======= -->
		  										
                          <?php
                  if(count($this->view->minhas_postagem) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="">
                        <p><small>Ainda não fizeste nenhuma publicação!</small></p>
                        </center>
                       
                    <?php } else {
                          $cont = 0;
                          foreach($this->view->minhas_postagem as $key => $valor){ 
                        
                            ?>
                                  <div class="row mb-3" id = "postagem<?= $valor['id'] ?>">
                                    <div class="col-12">
                                      <div class="card">
                                        <div class="card-header">
                                          <div class="row">
                                            <div class="col-2">
                                                <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?=  $valor['nome_foto']?>" style="width: 3rem; height: 3rem; object-fit: cover; height: 3rem; object-fit: cover;" />
                                            </div>
                                            <div class="col-7">
                                              <h5 ><?= $valor['nome'] ?> </br> <small> <?=  $valor['data']?></small> </h5>
                                            </div>
                                            <?php if($valor['id_usuario'] == $_SESSION['id']){  ?>
                                            <div class="col-3">
                                            <div class="row">
                                              <div class="col-2">
                                              <img onclick = "apagar_modal(<?= $valor['id'] ?>)"  src="assets/img/delete.png" style="width: 1rem;" />
                                                </div>
                                                <div class="col-2">
                                                    <a onclick = "editar(<?= $valor['id'] ?>,'<?= $valor['tweet'] ?>')"><img  src="assets/img/edit.png" style="width: 1rem;" /></a>
                                                </div>
                                              </div>
                                            </div>
                                            <?php  }?>
                                            
                                          </div>
                                        </div>
                                         <div class="container mb-0">
                                         <h5><b><?= $valor['titulo'] ?></b></h5>
                                         </div>
                                         
                                            <div class="card-header" id = "post_<?= $valor['id'] ?>">
                                              <p style="width: 100%;">
                                                <?= $valor['tweet'] ?>
                                              </p>
                                            </div>
                                      <?php if($valor['imagem_carregada'] != 'indefinido'){  ?>
                                      <img class = "card-img-top" src="/imagem_carregada/<?=  $valor['imagem_carregada']?>" />
                                     
                                      <?php }?>
                                      <?php if($valor['pdf'] != 'indefinido'){ 
                                    if($_SESSION['tema'] == 'layout'){
                                    ?>
                                    <img class = "card-img-top" src="/imagem_carregada/imagempdf.jpg" />
                                      <div style = " background: #000000;">
                                       <h5 class = "mx-2"><small><?= $valor['pdf_original'] ?></small></h5>
                                       <p class = "mx-3 mt-0"><small><?= $valor['pdf_descricao'] ?></small></p>
                                       <div>
                                       <a href="./ficheiro_pdf/<?= $valor['pdf'] ?>" class = "btn btn-light mr-2"   style="width: 95%; margin: 10px; margin-top: -10px; " >
                                           <b class = "text-primary">Baixar PDF</b>     
                                       </a>
                                       </div>
                                      </div>
                                      <?php }else{?>
                                        <img class = "card-img-top" src="/imagem_carregada/imagempdf.jpg" />
                                        <div style = " background: #ffaa0d;">
                                       <h5 class = "mx-2"><small><?= $valor['pdf_original'] ?></small></h5>
                                       <p class = "mx-3 mt-0"><small><?= $valor['pdf_descricao'] ?></small></p>
                                       <div>
                                       <a href="./ficheiro_pdf/<?= $valor['pdf'] ?>" class = "btn btn-light mr-2"   style="width: 95%; margin: 10px; margin-top: -10px; " >
                                           <b class = "text-primary">Baixar PDF</b>     
                                       </a>
                                       </div>
                                      </div>
                                      <?php }}?>
                                         
                                          <?php if($valor['id_usuario'] != $_SESSION['id']){  ?>
                                            <div class="row">
                                  
                                            <div class="col-6">
                                                <div class = "text-center">
                                                      <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "like(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                          <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img  src="assets/img/like.png" style="width: 1rem;" /></p>  
                                                          
                                                      </button>

                                                </div>
                                            </div>
                                            <div class="col-6">
                                                <div class = "text-center">
                                                      <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "salvar(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                          <p style="width: 90%; margin: 0px; " id = "numeroSalvar<?= $valor['id'] ?>"><?= $this->view->num_arquivado[$cont] ?> <img  src="assets/img/salve.png" style="width: 1rem;" /></p>  
                                                          
                                                      </button>
                                                </div>
                                            </div>
                                            
                                        </div> 
                                       
                                        <?php  } else{?>
                                          <div class="row">
                                  
                                          <?php if ($valor['estado_like'] == 0) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "like(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)"  src="assets/img/coracao1.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <?php if ($valor['estado_like'] == 1) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"><?= $this->view->num_like[$cont] ?> <img onclick = "remover_like(<?= $valor['id'] ?>)"  src="assets/img/coracao.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "salvar(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                <p style="width: 90%; margin: 0px; " id = "numeroSalvar<?= $valor['id'] ?>"><?= $this->view->num_arquivado[$cont] ?> <img  src="assets/img/salve.png" style="width: 1rem;" /></p>  
                                                
                                            </button>
                                      </div>
                                  </div>
                                  
                              </div> 
                                      <?php  }?>
                                      </div>
                                    </div>
                            </div>
                        <?php $cont++; }}?>
                   <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                          </div>
                        </div>
                    </div>
                  </div>

                </div>
              </div>  
          <!-- ======= FIM DA AREA ONDE VC VE TODAS AS POSTAGEM ======= -->


          </div>
                  
            </div>
        </div>
        </section>
</main>
        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    
<div style = "background-color: rgba(0, 0, 0, 0.1);">
<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Definição</h5>
       
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-12">
          <center>
          <a href="/trocatema">
              <button style = "width: 90%;" class = "btn btn-primary">Trocar tema</button>
            </a>
          </center>
            
          </div>
      </div>
      <hr>
      <b>Nome:</b>
          <div class="row mb-3">
              <div class="col-9">
                <input id = "novo_nome" type="text" class = "form-control" value = "<?=  $_SESSION['nome'] ?>">
              </div>
              <div class="col-3">
                <button onclick = "trocar_nome()" class = "btn btn-primary">Alterar</button>
              </div>
          </div>

          

<hr>
          <b>Palavra passe:</b>
          <div class="row mb-3">
              <div class="col-4">
              <label for="">Nova Senha</label>
                <input id = "nova_senha" type="password" class = "form-control" value = "">
              </div>
              <div class="col-4">
              <label for="">Confirmar</label>
                <input id = "confirmar_senha" type="password" class = "form-control" value = "">
              </div>
              <div class="col-4">
              <label for="">Senha atual</label>
                <input id = "senha_antiga" type="password" class = "form-control" value = "">
              </div>
          </div>
          <div class="row">
              <div class="col-12 m-auto">
                <center>
                <button onclick = "trocar_senha()" style="width: 90%; margin: 0px; "  class = "btn btn-primary">Alterar</button>
                </center>
              </div>
          </div>
          <div class="modal-footer">
              <div class="col-12 m-auto">
                <center>
                <a href="/iliminar_conta"><button style="width: 90%; margin: 0px; "  class = "btn btn-danger">Eliminar Conta</button></a>
                </center>
              </div>
          </div>
          </div>
          
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
</div>
    

    

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
