


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      <?php if($_SESSION['perfil'] == '2'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline_professor"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/professor"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/.png" alt="Publico"></a></li>
          <li><a href="/tarefa_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_enviadas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/.png" alt="Publico"></a></li>
          <li><a href="/alunos"><img id = "aluno" style="width: 1.7rem;" src="assets/img/menu/aluno/.png" alt="Publico"></a></li>
          <li><a href="/turma"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php } else?>
      <?php if($_SESSION['perfil'] == '1'){?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas" id = "duvida"><img style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php }?>
      
    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
      
      <div class="row">
          <div class="container">
            <div class="row" id = "top">
  

    <div class="col-lg-3 d-none d-lg-block" id = "fixoa">
    


  <div class="card mb-3">
      <div class="row" >
        <div class="col-12">
          <div class=" align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                  <a href="/pergunta_respondida">
                    <div class="row">
                      <div class="col-4">
                        <img src="/fotos_de_perfil/foto_perfil.png" style="width: 3.5rem;" />
                      </div>
                      <div class="col-8">
                        <p style="margin-top: 8%;">Pergunta Respondidas</p>  
                      </div>
                    </div>
                  </a>  
          </div>
        </div>
      </div>
    </div>
    <div class="card mb-3 border border-primary">
      <div class="row" >
        <div class="col-12">
          <div class=" align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                  <a href="/perguntas_enviadas">
                    <div class="row">
                      <div class="col-4">
                        <img src="/fotos_de_perfil/foto_perfil.png" style="width: 3.5rem;" />
                      </div>
                      <div class="col-8">
                        <p style="margin-top: 8%;">Perguntas Enviadas</p>  
                      </div>
                    </div>
                  </a>  
          </div>
        </div>
      </div>
    </div>
    <div class="card mb-3">
      <div class="row" >
        <div class="col-12">
          <div class=" align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                  <a href="#">
                    <div class="row">
                      <div class="col-4">
                        <img src="/fotos_de_perfil/foto_perfil.png" style="width: 3.5rem;" />
                      </div>
                      <div class="col-8">
                        <p style="margin-top: 8%;">Respostas Corrigidas</p>  
                      </div>
                    </div>
                  </a>  
          </div>
        </div>
      </div>
    </div>
    

</div>


<div class="col-lg-1 d-none d-sm-block" id = "principal"></div>

<!-- ======= AREA DOS POST ======= -->
<!-- ======= AREA DOS POST ======= -->
<!-- ======= AREA DOS POST ======= -->

<div class="col-lg-6 col-md-12 col-sm-12">
  

    <!-- ======= AREA ONDE PODES VER TODAS AS POSTAGEM ======= -->

    <div class="row">
        <div class="col-lg-12" data-aos="fade-up">
          <div class="row mt-0">
            <div class="col-12">
                <div class="col-lg-12" data-aos="fade-up" >
                  <div>
                  <!-- ======= CARD DE POSTAGEM ======= -->
                  
                  <?php foreach($this->view->duvidas as $key => $valor){?>
                          <div class="row mb-2">
                            <div class="col-12">
                              <div class="card">
                                <div class="row m-2">
                                  <div class="col-12">
                                    <div class="card">
                                        <div class="row">
                                            <div class="col-2 m-2">
                                                <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto']?>" style="width: 2.5rem;" />

                                            </div>
                                            <div class="col-8 m-2">
                                              <h5><?= $valor['nome'] ?> / <small class = "text-success"> Destino</small></br> <small><?= $valor['data'] ?></small> </h5>
                                            </div>

                                        </div>
                                    </div>
                                  </div>
                                </div>
                          <div class="row m-2">
                            <div class="col-12">
                              
                                
                                        
                                <div class="card-header">
                                  <div class="row">
                                    <div class="col-2">
                                    <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $_SESSION['foto_perfil']?>" style="width: 2rem;" />
                                    </div>
                                    <div class="col-7">
                                      <h5 ><?= $_SESSION['nome'] ?> / <small class = "text-success">Pergunta</small> </h5>
                                    </div>
                                  </div>
                                </div>
                                
                                  <div style="margin: 10px;">
                                    
                                        <h4><?= $valor['titulo'] ?></h4>
                                    
                                    <div class="card-header">
                                      <p style="width: 100%;">
                                        <?= $valor['duvida'] ?>
                                      </p>
                                    </div>
                                  </div>
                                  
                                <div class="row">
                                  
                                    <div class="col-6">
                                        <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                            <a href = "/duvida?id_duvida=<?= $valor['id_duvida'] ?>" class = "btn btn-danger" style="width: 95%; margin: 10px; " type="submit"  >
                                              <img style="width: 1rem;" class="text-center" src="assets/img/erro.png" alt="">
                                            </a>
                                          
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                            <button class = "btn btn-info" style="width: 95%; margin: 10px; " type="submit"  >
                                              <img style="width: 1rem;" class="text-center" src="assets/img/edit.png" alt="">
                                            </button>
                                          
                                        </div>
                                    </div>
                                    
                                </div>
                                        
                                
                              </div>
                           
                          </div>
                              </div>
                            </div>
                          </div>
                <?php  }?>
           <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                  </div>
                </div>
            </div>
          </div>

        </div>
      </div>  
  <!-- ======= FIM DA AREA ONDE VC VE TODAS AS POSTAGEM ======= -->


  </div>
  <!-- ======= FIM DA AREA DOS POST ======= -->


</div>

</div>
            </div>
          </div>
        </div>
    </section>

        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

    

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
