


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas" id = "duvida"><img style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar3.png" alt="Publico"></a></li>
        </ul>
      </nav>

    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
        <div class="row">
         
            <div class="container">

            <div class="row" id = "top">
  

   
<div class="col-lg-7 m-auto col-md-12 col-sm-12">
          

            <!-- ======= AREA ONDE PODES VER TODAS AS POSTAGEM ======= -->

            <div class="row">
                <div class="col-lg-12" data-aos="fade-up" >
                  <div class="row mt-0">
                    <div class="col-12">
                        <div class="col-lg-12" data-aos="fade-up" >
                          <div>
		                      <!-- ======= CARD DE POSTAGEM ======= -->
		  										
                         
                                  <div class="row mb-3">
                                    <div class="col-12">

                                      <div class="card">
                                        
                                        <div class="card-body">
                                        <form action="pesquisar_professor" method="get">
                                            <div class="row">
                                               
                                                   <div class="col-lg-10 mr-0">
                                                        <input name = "procurado" class = "form-control" type="text">
                                                    </div>
                                                    <div class="col-2 ml-0">
                                                        <button class = "btn btn-primary"><img style="width: 1rem;" src="assets/img/pesquisar.png" alt="Publico"></button>
                                                    </div>
                                               
                                            </div>
                                         </form>
                                        </div>
                                       
                                    </div>
                                 </div>


                                 
                                
                            </div>
                            <?php
                            $listagem;
                            if(!isset($this->view->vazio)){
                                $listagem = $this->view->lista_professores;
                            }
                            else{
                                $listagem =  $this->view->procurados;
                            }
                            foreach($listagem as $key => $valor){ 
                             
                              ?>
                            <div class="row mb-3" id = "professor<?= $valor['id'] ?>">
                              <div class="col-12">
                                <div class="card">
                                  <div class="card-body">
                                    <div class="container">
                                    <div class="row">
                                    </div>
                                    <div class="row">
                                    
                                                
                                            <div class="col-lg-3 d-none d-lg-block text-center">
                        <a href="/professor?id_professor=<?= $valor['id'] ?>">
                        <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>" style="width: 6rem; height: 6rem; object-fit: cover;" />
                        </a>
                                                
                                            
                                                <div class="row">
                                                <?php if($valor['avaliacao'] < 1){  ?>
                                              
                                                        <div class="estrela">
                                                            <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                            <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                            
                                                            <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                            <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                            <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                            <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                            <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                            
                                                </div>
                                                <?php } ?>
                                                <?php if($valor['avaliacao'] >= 1 && $valor['avaliacao'] < 2){  ?>
                                              
                                              <div class="estrela">
                                                  <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                  <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                  <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                  
                                                  <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                  <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                  <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                  <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                  
                                      </div>
                                      <?php } ?>
                                      <?php if($valor['avaliacao'] >= 2 && $valor['avaliacao'] < 3){  ?>
                                              
                                                <div class="estrela">
                                                  <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                  <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                  <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                  
                                                  <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                  <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                  <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                  <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                  <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                  
                                                </div>
                                      <?php } ?>
                                      <?php if($valor['avaliacao'] >= 3 && $valor['avaliacao'] < 4){  ?>
                                              
                                              <div class="estrela">
                                                <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                
                                                <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                
                                              </div>
                                    <?php } ?>
                                    <?php if($valor['avaliacao'] >= 4 && $valor['avaliacao'] < 5){  ?>
                                              
                                              <div class="estrela">
                                                <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                
                                                <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela1.png" alt=""></label>
                                                <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                
                                              </div>
                                    <?php } ?>
                                    <?php if($valor['avaliacao'] >= 5 ){  ?>
                                              
                                              <div class="estrela">
                                                <input type="radio" id = "vazio" name = "estrela" value = "" checked>

                                                <label for="estrela_um" ><img id = "estrela1" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = " estrela" type="radio" id = "estrela_um" name = "estrela" value = "1">
                                                
                                                <label  for="estrela_dois" ><img  id = "estrela2" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_dois" name = "estrela" value = "2">

                                                <label  for="estrela_tres" ><img  id = "estrela3" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_tres" name = "estrela" value = "3">

                                                <label  for="estrela_quatro" ><img id = "estrela4" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-1 estrela" type="radio" id = "estrela_quatro" name = "estrela" value = "4">

                                                <label  for="estrela_cinco" ><img id = "estrela5" style="width: 1.5rem;" src="assets/img/estrelas/estrela2.png" alt=""></label>
                                                <input class = "mr-2 estrela"type="radio" id = "estrela_cinco" name = "estrela" value = "5">
                                                
                                              </div>
                                    <?php } ?>
                                                   
                                                    </div>
                                                   
                                                </div>

                                                <div class="col-lg-8 col-sm-12">
                                                <h4 ><?= $valor['nome'] ?></h4>
                                                <p ><img style="width: 1.3rem;" src="assets/img/local.png" alt="Publico"> <?= $valor['cidade'] ?>/<?= $valor['municipio'] ?>/<?= $valor['bairro'] ?></p>
                                                <p ><img style="width: 1.3rem;" src="assets/img/escola.png" alt="Publico"> <?= $valor['curso'] ?></p>
                                                <div class="row">
                                                   
                                                  
                                                    <div class="col-6">
                                                        <button onclick = "enviar_pedido(<?= $valor['id'] ?>)" style = "width: 100%;" class = "btn btn-primary">Adicionar</a>
                                                    </div>
                                                    <div class="col-6">
                                                        <a href="/professor?id_professor=<?= $valor['id'] ?>"><button style = "width: 100%;" class = "btn btn-info">Ver perfil</a></a>
                                                    </div>
                                                </div>
                                                </div>
                                                
                                                    
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          <?php } ?>
                        </div>
                    </div>
                  </div>

               
            </div>
         </div>
            
          <!-- ======= FIM DA AREA DOS POST ======= -->

        

          

        </div>

      </div>
   
    </section>
        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

   

  </main><!-- End #main -->
  <div class="col-lg-8">
  <!-- Modal -->

  

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
