


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline_professor"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/professor"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/.png" alt="Publico"></a></li>
          <li><a href="/tarefa_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_enviadas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/.png" alt="Publico"></a></li>
          <li><a href="/alunos"><img id = "aluno" style="width: 1.7rem;" src="assets/img/menu/aluno/.png" alt="Publico"></a></li>
          <li><a href="/turma"><img style="width: 1.7rem;" src="assets/img/turma.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
        </ul>
      </nav>
    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
      
      <div class="row">

        <div class="col-lg-6 col-md-12 col-sm-12 m-auto">
            
                  <div class="row mt-0">
                    <div class="col-12">
                        <div class="col-lg-12"  >
                          <div>
		                      <!-- ======= CARD DE POSTAGEM ======= -->
		  										
                          <div class="row">
                <div class="col-lg-12"  >
                <div class="row">
                    <div class="col-6">
                    <div class="card mb-3">
                      <div class="row" >
                        <div class="col-12">
                          <div class=" align-items-stretch"  data-aos-delay="100">
                            <a href="/alunos">
                                    <div class="row">
                                      <div class="col-4">
                                      <img src="/assets/img/sobre_pessoal/pedido.png" style="width: 3rem;" />
                                      </div>
                                      <div class="col-8">
                                        <p></br>Pedidos</p>  
                                      </div>
                                    </div>
                                  </a>
                          </div>
                        </div>
                      </div>
                    </div>
                    </div>
                    <div class="col-6">
                    <div class="card mb-3   border border-primary">
                        <div class="row" >
                          <div class="col-12">
                            <div class=" align-items-stretch" data-aos-delay="100">
                                    <a href="/listar_aluno">
                                      <div class="row">
                                        <div class="col-4">
                                          <img src="/assets/img/sobre_pessoal/alunos.png" style="width: 3rem;" />
                                        </div>
                                        <div class="col-8">
                                          <p></br>Listar Meus Alunos</p>  
                                        </div>
                                      </div>
                                    </a>
                                  
                            </div>
                          </div>
                          
                        </div>

                      </div>
                    </div>
                </div>
                                  <div class="row mb-3">
                                    <div class="col-12">

                                      <div class="card">
                                        
                                        <div class="card-body">
                                        <form action="pesquisar_professor" method="get">
                                            <div class="row">
                                               
                                                   <div class="col-lg-10 mr-0">
                                                        <input name = "procurado" class = "form-control" type="text">
                                                    </div>
                                                    <div class="col-2 ml-0">
                                                        <button class = "btn btn-primary"><img style="width: 1rem;" src="assets/img/pesquisar.png" alt="Publico"></button>
                                                    </div>
                                               
                                            </div>
                                         </form>
                                        </div>
                                       
                                    </div>
                                 </div>


                                 
                                
                            </div>
                            <?php
                            
                            foreach($this->view->lista_alunos as $key => $valor){  ?>
                            <div class="row mb-3">
                                    <div class="col-12">

                                      <div class="card">
                                       
                                        <div class="card-body">
                                            <div class="row">
                                                
                                                <div class="col-1">
                                                <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>" style="width: 3rem; margin-left: 0px;" />
                                                
                                              </div>

                                                <div class="col-8">
                                                    <h4 class = "mt-2 ml-3"><?= $valor['nome'] ?></h4>
                                                </div>

                                                <div class="col-3 ml-0">
                                                <a href="#"style = "width: 100%;" class = "btn btn-primary">Mensagem</a>
                                                </div>
                                               
                                                
                                                
                                                

                                            </div>

                                        </div>
                                    </div>
                                    
                                 </div>

                        
                   <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                          </div>
                          <?php } ?>
                        </div>
                    </div>
                  </div>

                </div>
              </div>  
            </div>
         </div>
            
          <!-- ======= FIM DA AREA DOS POST ======= -->

        

          

        </div>

      </div>
   
    </section>
        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

   

  </main><!-- End #main -->
  <div class="col-lg-8">
  <!-- Modal -->

  

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
