


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      <?php if($_SESSION['perfil'] == '2'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline_professor"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/professor"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/.png" alt="Publico"></a></li>
          <li><a href="/tarefa_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_enviadas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/.png" alt="Publico"></a></li>
          <li><a href="/alunos"><img id = "aluno" style="width: 1.7rem;" src="assets/img/menu/aluno/.png" alt="Publico"></a></li>
          <li><a href="/turma"><img style="width: 1.7rem;" src="assets/img/turma2.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php } else?>
      <?php if($_SESSION['perfil'] == '1'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas" id = "duvida"><img style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma2.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php }?>
    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
    
  
            <div class="row" id = "top">
  
 

<!-- ======= AREA DOS POST ======= -->
<!-- ======= AREA DOS POST ======= -->
<!-- ======= AREA DOS POST ======= -->

<div class="col-lg-6 col-md-12 col-sm-12 m-auto">
  <div class="row">
        <div class="col-12" id = "formulario">
            <a onclick = "criar_turma()" class = "btn btn-primary" style="width: 95%; margin: 10px; " type="submit"  >
                 Nova Turma  
            </a>
        </div>
  </div>

    <div id = "turma_lista">
    
    </div>


</div>

</div>
    </section>

        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

    

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
