


  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
     
      
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas" id = "duvida"><img style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma2.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
     
    </div>
  </header><!-- End Header -->

 

  <main>

    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
    <!-- ======= SENSSÃO ======= -->
  
    <section id="contact" class="contact">
    
  
            <div class="row" id = "top">
  
 

<!-- ======= AREA DOS POST ======= -->
<!-- ======= AREA DOS POST ======= -->
<!-- ======= AREA DOS POST ======= -->

<div class="col-lg-6 col-md-12 col-sm-12 m-auto">
  

    <!-- ======= AREA ONDE PODES VER TODAS AS POSTAGEM ======= -->

    
                  <!-- ======= CARD DE POSTAGEM ======= -->
                  
                  <?php
                  if(count($this->view->turma) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="" style="margin-top: 20%;">
                        <p><small>Ainda não estas incluído em uma turma!</small></p>
                        </center>
                       
                    <?php } else {  foreach($this->view->turma as $key => $valor){?>
                          <div class="row mb-2">
                            <div class="col-12">
                              
                          <div class="row m-2">
                            <div class="col-12">
                              <div class="card">
                                
                                        
                                <div class="card-header">
                                <div class="row">
                                <div class="col-12 text-center">
                                    <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['foto_turma'] ?>" style="width: 5rem;" />
                                    </div>
                                </div>
                                  <div class="row">
                                    
                                    <div class="col-8 m-auto text-center">
                                      <h2 ><?= $valor['nome_turma'] ?></h2>
                                      <small ><?= $valor['descricao_turma'] ?></small>
                                    </div>
                                    
                                    
                                  </div>
                                </div>
                                
                                  <div style="margin: 10px;">
                                    
                                <div class="row">
                                  
                                    <div class="col-12">
                                        <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                            <a href = "/entrar_turma?id_turma=<?= $valor['id_turma'] ?>" class = "btn btn-primary" style="width: 95%; margin: 10px; " type="submit"  >
                                                Entrar 
                                            </a>
                                          
                                        </div>
                                    </div>
                                   
                                    
                                </div>
                                            
                                
                              </div>
                            </div>
                          </div>
                              </div>
                           
                <?php  }}?>
           <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

  <!-- ======= FIM DA AREA DOS POST ======= -->


</div>

</div>
    </section>

        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->

    

    

    

    

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
