

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

    <div class="logo float-left">
        <img src="./img/teach_header.png" alt="" style="width: 10rem;"> 
      </div>
      <?php if($_SESSION['perfil'] == '2'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline_professor"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/professor"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/.png" alt="Publico"></a></li>
          <li><a href="/tarefa_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_enviadas"><img id = "duvida" style="width: 1.7rem;" src="assets/img/menu/duvida/.png" alt="Publico"></a></li>
          <li><a href="/alunos"><img id = "aluno" style="width: 1.7rem;" src="assets/img/menu/aluno/.png" alt="Publico"></a></li>
          <li><a href="/turma"><img style="width: 1.7rem;" src="assets/img/turma2.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php } else?>
      <?php if($_SESSION['perfil'] == '1'){ ?>
        <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/timeline"><img style="width: 1.7rem;" src="assets/img/home.png" alt="Publico"></a></li>
          <li><a href="/aluno"><img style="width: 1.7rem;" src="assets/img/perfil.png" alt="Publico"></a></li>
          <li><a href="/chat"><img style="width: 1.7rem;" src="assets/img/mensagem.png" alt="Publico"></a></li>
          <li><a href="/notificacao"><img id = "notificacao" style="width: 1.7rem;" src="assets/img/menu/notificacao/0.png" alt="Notificação"></a></li>
          <li><a href="/pergunta_respondida"><img id = "tarefa" style="width: 1.7rem;" src="assets/img/menu/Tarefa/0.png" alt="Publico"></a> </li>
          <li><a href="/meus_professor"><img style="width: 1.7rem;" src="assets/img/professor.png" alt="Publico"></a> </li>
          <li><a href="/duvidas_respondidas" id = "duvida"><img style="width: 1.7rem;" src="assets/img/menu/duvida/0.png" alt="Publico"></a></li>
          <li><a href="/turmas"><img style="width: 1.7rem;" src="assets/img/turma2.png" alt="Publico"></a></li>
          <li><a href="/timeline_publico"><img style="width: 1.7rem;" src="assets/img/public.png" alt="Publico"></a></li>
          <li><a href="/pesquisar"><img style="width: 1.7rem;" src="assets/img/pesquisar.png" alt="Publico"></a></li>
        </ul>
      </nav>
      <?php }?>

    </div>
  </header><!-- End Header -->

  

  <main>

  <section id="contact" class="contact">
      
        

      <div class="row" id = "top">
      
        <div class="col-lg-3 d-none d-lg-block" id = "fixo">
              <div class=" mb-3">
                <div class="row m-3" >
                  <div class="col-12">
                    <div class=" align-items-stretch text-center" data-aos="fade-up" data-aos-delay="100">
                    <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $this->view->dados_turma[0]['foto_turma'] ?>" style="width: 8rem;" />
                          <h3 style = "color: black;"><?= $this->view->dados_turma[0]['nome_turma'] ?></h3>
                          <p><?= $this->view->dados_turma[0]['descricao_turma'] ?></p>
                    </div>
                  </div>
                </div>
              </div>
          <?php if($this->view->dados_turma[0]['id_adm'] == $_SESSION['id']){  ?>
            <small class = "d-none d-lg-block"><b>Meus Alunos</b></small>
            <?php
                  if(count($this->view->listar_alunos) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="">
                        <p><small>Ainda não tens nenhum aluno para listar!</small></p>
                        </center>
                       
                    <?php } else { foreach($this->view->listar_alunos as $key => $valor){  ?>
                        <div class="mb-3" id = "aluno<?= $valor['id'] ?>">
                        <div class="row" >
                            <div class="col-12">
                            <div class=" align-items-stretch" data-aos-delay="100">
                                    <a>
                                        <div class="row mt-2 ml-1">
                                        <div class="col-2">
                                        <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>" style="width: 3rem; margin-left: 0px;" />
                                        </div>
                                        <div class="col-7">
                                            <p style="margin-top: 8%;"><?= $valor['nome'] ?></p>  
                                        </div>
                                        <div class="col-2">
                                            <img onclick = "add_turma(<?= $valor['id'] ?>,<?= $this->view->dados_turma[0]['id_turma'] ?>)"  src="assets/img/turma/add.png" style="width: 2rem;" />
                                        </div>
                                        
                                        </div>
                                    </a>  
                            </div>
                            </div>
                        </div>
                        </div>
                    <?php }}?>
                    <small class = "d-none d-lg-block"><b>Minhas turmas</b></small>
                      <?php  foreach($this->view->turma as $key => $valor){ ?>
                          <div class="row mt-3">
                              <div class="col-2  mr-3">
                                <img class="rounded-circle border border-primary m-1" src="/fotos_de_perfil/<?= $valor['foto_turma'] ?>" style="width: 3rem;" />
                              </div>
                            <div class="col-7">
                              <p style = "margin-top: 10%;" class = "d-none d-lg-block"><?= $valor['nome_turma'] ?></p>  
                            </div>
                            <div class="col-1" style = "margin-top: 4%;">    
                              <div class="row" >
                              <a href = "/entrar_turma?id_turma=<?= $valor['id_turma'] ?>">
                                  <img src="/assets/img/sobre_pessoal/entrar.png" style="width: 2rem;" />
                                </div>
                              </a>
                            </div>
                          </div>
                      <?php  } ?>

                     <small class = "d-none d-lg-block mt-3"><b>Carregar Foto De Perfil</b></small>
                        <div class="row mb-5" >
                            <div class="col-12">
                            <div class=" align-items-stretch" data-aos-delay="100">
                            <div class="row">
                              <form class = "m-2" action="/carregar_foto_perfil" method="post" enctype = "multipart/form-data">
                              <div class="row m-auto">
                                  <div class="col-8">
                                    <input id = "imagem" class = "uploadbox" name = "imagem" type="file">
                                  </div>
                                  <div class="col-4">
                                  <input type="hidden" name = "turma" value = "<?= $this->view->id_turma ?>">
                                              
                                    <button style = " width: 100%;" class = "btn btn-primary" type="submit">
                                      +
                                    </button>
                                  </div>
                                                
                                </div>
                              </form>
                            </div>
                            </div>
                        </div>
                        </div>

                     
                           
                                        <?php }?>
            

        </div>


            <div class="col-lg-1 d-none d-sm-block" id = "principal"></div>


<!-- =================================================================== -->
<!-- ======================= MENU DE PUBLICIDADE======================== -->
<!-- =================================================================== -->
                    <div class="col-lg-3 d-none d-lg-block" id = "fixoc">
                    <b>Membros</b>
                    <?php
                  if(count($this->view->listar_membros) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="" style="margin-top: 40%;">
                        <p><small>Ainda não tens nenhum membro nesta turma!</small></p>
                        </center>
                       
                    <?php } else { foreach($this->view->listar_membros as $key => $valor){  ?>
                      <div class=" mb-3">
                      <div class="row" id = "aluno<?= $valor['id'] ?>">
                          <div class="col-12">
                          <div class=" align-items-stretch" data-aos-delay="100">
                                      <div class="row mt-2 ml-1">
                                      <div class="col-2">
                                      <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>"  style="width: 2.5rem; height: 2.5rem; object-fit: cover;" />
                                      </div>
                                      <div class="col-7">
                                          <p style="margin-top: 8%;"><?= $valor['nome'] ?></p>  
                                      </div>
                                      <?php if($this->view->dados_turma[0]['id_adm'] == $_SESSION['id']){  ?>
                                      <div class="col-2">
                                            <img onclick = "remove_turma(<?= $valor['id'] ?>,<?= $this->view->dados_turma[0]['id_turma'] ?>)"  src="assets/img/turma/remove.png" style="width: 2rem; cursor: pointer;" />
                                        </div>
                                        <?php } ?>
                                      </div>
                          </div>
                          </div>
                      </div>
                      </div>
                  <?php }}?>
                        
                        
                    </div>

                    <!-- ======= AREA DOS POST ======= -->
                    <!-- ======= AREA DOS POST ======= -->
                    <!-- ======= AREA DOS POST ======= -->

                    <div class="col-lg-5 col-md-12 col-sm-12" >
                    <!-- <div class="row mb-3">
                      <div class="col-12">
                        <img class = "card-img-top" src="/imagem_carregada/code.jpg" style = "height: 200px;" />
                      </div>
                    </div> -->
                           
                            <!-- ======= FIM DO CARD DE PUBLICAÇÃO ======= -->
                            
                            <div class="row">
                                    <div class="col-lg-12" data-aos="fade-up">
                                    <div class="row mb-2">
                                    <div class="col-6">
                                      <button data-toggle="modal" data-target="#sobre" style = "width: 100%" Class = "btn btn-primary">Sobre Grupo</button>
                                    </div>
                                    <div class="col-6">
                                      <button data-toggle="modal" data-target="#membros" style = "width: 100%" Class = "btn btn-primary">Membros</button>
                                    </div>
                                  </div>
                                    <div class="row mt-0">
                                        <div class="col-12">
                                            <div class="col-lg-12" data-aos="fade-up" >
                                            <div>
                                                <!-- ======= CARD DE POSTAGEM ======= -->
                                                                    
                                                                        
                                                   <form action="/publicar_turma" method="post" enctype = "multipart/form-data">
                                                      <div class="row mb-3">
                                                            <div class="col-12">
                                                              <div class="card">
                                                              <input type="hidden" name = "id_turma" value = "<?= $this->view->id_turma ?>">
                                                                    <div class="card-body">
                                                                        <div class="row mb-2">
                                                                           
                                                                        <div class="col-1 mr-4">
                                                                        <!-- <a href="./ficheiro_pdf/A_Ditadura_Da_Beleza_E_A_Revolucao_Das_Mulheres_-_Augusto_Cury.pdf.zip">Download</a> -->
                                                                        <input type='file' name="imagem" accept="image/x-png,image/jpeg" id="imagem" hidden />
                                                                        <div>
                                                                            <label for="imagem"><img class=" border-primary" src="/assets/img/img.png" style="width: 2.5rem;" /></label>
                                                                        </div>
                                                                      </div>

                                                                      <div class="col-2">
                                                                        <!-- <a href="./ficheiro_pdf/A_Ditadura_Da_Beleza_E_A_Revolucao_Das_Mulheres_-_Augusto_Cury.pdf.zip">Download</a> -->
                                                                        <input type='file' name="pdf"  id="pdf" hidden />
                                                                        <div>
                                                                            <label for="pdf"><img class=" border-primary" src="/assets/img/file.png" style="width: 2.5rem;" /></label>
                                                                        </div>
                                                                      </div>
                                                                            
                                                                        </div>
                                                                       
                                                                        
                                                                        
                                                                        <div class="row mb-2">
                                                                            <div class="col-12">
                                                                                <input id = "titulo" class = "form-control" name = "titulo" type="text" placeholder = "Título">
                                                                            </div>
                                                                        </div>
                                                                        <div class="row">
                                                                            <div class="col-12">
                                                                                <textarea id = "postagem" class="form-control" name="tweet" rows="3" data-msg="Escreva alguma dúvida!" placeholder="Escreva aqui a tua dúvida"></textarea>

                                                                            </div>
                                                                        </div>
                                                                        <small><h5 id = "mensagem" class = "text-success text-center"></h5></small>
                                                                    </div>
                                                                

                                                                <div class="row">
                                                              
                                                                    <div class="col-12">
                                                                        <div >
                                                                        
                                                                        <div class="text-center mb-2">
                                                                      
                                                                        <button style = " width: 50%; margin-top: -20px;" class = "btn btn-primary" type="submit">
                                                                          Carregar Publicação
                                                                        </button>
                                                                        </div>

                                                                        
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-7 m-auto">
                                                                    <?php if(isset($_GET['men'])){  ?>
                                                                        <small class = "text-danger">O teu conteúdo não foi publicado Tente novamente</small>
                                                                    <?php } ?>
                                                                    </div>
                                                                </div>
                                                              </div>
                                                            </div>
                                                      </div>
                                      </form>
                        
                   <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                          </div>
                        </div>
                    </div>
                  </div>

                </div>
              </div>  

            <!-- ======= AREA ONDE PODES VER TODAS AS POSTAGEM ======= -->

              <div class="row">

                <div class="col-lg-12" data-aos="fade-up">
                  <div class="row">
                    <div class="col-12">
                        <div class="col-lg-12" data-aos="fade-up" >
                          <div>
		                      <!-- ======= CARD DE POSTAGEM ======= -->
		  										
                          <?php 
                  $cont = 0;
                  foreach($this->view->listar_postagem as $key => $valor){ 
                
                    ?>
                          <div class="row mb-3" id = "postagem<?= $valor['id'] ?>">
                            <div class="col-12">
                              <div class="card">
                                <div class="card-header">
                                  <div class="row">
                                    <div class="col-2">
                                    <?php if($valor['id_usuario'] == $_SESSION['id']){  ?>
                                      <a href="/aluno"><img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?=  $valor['nome_foto']?>" style="width: 3rem; height: 3rem; object-fit: cover; height: 3rem; object-fit: cover;" /></a>
                                    <?php  }else ?>
                                    <?php if($valor['id_usuario'] != $_SESSION['id']){  ?>
                                      <a href="/professor?id_professor=<?= $valor['id_usuario'] ?>"><img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?=  $valor['nome_foto']?>" style="width: 3rem; height: 3rem; object-fit: cover;" /></a>
                                    <?php  }else ?>
                                    </div>
                                    <div class="col-7">
                                      <h5 ><?= $valor['nome'] ?> </br> <small> <?=  $valor['data']?></small> </h5>
                                    </div>
                                    <?php if($valor['id_usuario'] == $_SESSION['id']){  ?>
                                    <div class="col-3">
                                      <div class="row">
                                          <div class="col-2">
                                              <img onclick = "deletar(<?= $valor['id'] ?>)"  src="assets/img/delete.png" style="width: 1rem;" />
                                          </div>
                                          <div class="col-2">
                                              <a onclick = "editar(<?= $valor['id'] ?>,'<?= $valor['tweet'] ?>')"><img  src="assets/img/edit.png" style="width: 1rem;" /></a>
                                          </div>
                                         
                                      </div>
                                    </div>
                                    <?php  }?>
                                    
                                  </div>
                                </div>
                                 <div class="container mb-0">
                                 <h5><?= $valor['titulo'] ?></h5>
                                 </div>
                                  <div class = "mx-3">
                                    <div id = "post_<?= $valor['id'] ?>">
                                      <p style="width: 100%;">
                                        <?= $valor['tweet'] ?>
                                      </p>
                                     
                                    </div>
                                    
                                  </div>
                                  <?php if($valor['imagem_carregada'] != 'indefinido' ){  ?>
                                      <img class = "card-img-top" src="/imagem_carregada/<?=  $valor['imagem_carregada']?>" />
                                     
                                  <?php }?>
                                  
                                  <?php if($valor['pdf'] != 'indefinido'){ 
                                    
                                    if($_SESSION['tema'] == 'layout'){
                                    ?>
                                    <img class = "card-img-top" src="/imagem_carregada/imagempdf.jpg" />
                                      <div style = " background: #000000;">
                                       <h5 class = "mx-2"><small><?= $valor['pdf_original'] ?></small></h5>
                                       <p class = "mx-3 mt-0"><small><?= $valor['pdf_descricao'] ?></small></p>
                                       <div>
                                       <a href="./ficheiro_pdf/<?= $valor['pdf'] ?>" class = "btn btn-light mr-2"   style="width: 95%; margin: 10px; margin-top: -10px; " >
                                           <b class = "text-primary">Baixar PDF</b>     
                                       </a>
                                       </div>
                                      </div>
                                      <?php }else{?>
                                        <img class = "card-img-top" src="/imagem_carregada/imagempdf.jpg" />
                                        <div style = " background: #ffaa0d;">
                                       <h5 class = "mx-2"><small><?= $valor['pdf_original'] ?></small></h5>
                                       <p class = "mx-3 mt-0"><small><?= $valor['pdf_descricao'] ?></small></p>
                                       <div>
                                       <a href="./ficheiro_pdf/<?= $valor['pdf'] ?>" class = "btn btn-light mr-2"   style="width: 95%; margin: 10px; margin-top: -10px; " >
                                           <b class = "text-primary">Baixar PDF</b>     
                                       </a>
                                       </div>
                                      </div>
                                      <?php }}?>
                                  <?php if($valor['id_usuario'] != $_SESSION['id']){  ?>
                                    <div class="row">
                                  <?php if ($valor['estado_like'] == 0) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"> <img onclick = "like(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)"  src="assets/img/coracao1.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <?php if ($valor['estado_like'] == 1) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"> <img onclick = "remover_like(<?= $valor['id'] ?>)"  src="assets/img/coracao.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  
                                  <?php }?>

                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "salvar(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                <p style="width: 90%; margin: 0px; " id = "numeroSalvar<?= $valor['id'] ?>"> <img  src="assets/img/salve.png" style="width: 1.4rem;" /></p>  
                                                
                                            </button>
                                      </div>
                                  </div>
                                  
                              </div> 
                              <div class="row">
                                  
                                  <div class="col-12">
                                      <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                        

                                        <a href="/comentarios?id=<?= $valor['id'] ?>&destino=turma&nome_turma=<?= $this->view->dados_turma[0]['nome_turma'] ?>&id_turma=<?= $_GET['id_turma'] ?>">
                                          <button class = "btn btn-light border border-primary" style="width: 95%; margin: 10px; " type="submit"  >
                                            <img style="width: 1.5rem;" class="text-center" src="assets/img/responder2.png" alt="">
                                          </button>
                                        </a>
                                        
                                          
                                        
                                       
                                      </div>
                                  </div>
                              </div>
                                <?php  } else{?>
                                <div class="row">
                                  
                                <?php if ($valor['estado_like'] == 0) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>"> <img onclick = "like(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)"  src="assets/img/coracao1.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <?php if ($valor['estado_like'] == 1) {?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " >
                                                <p style="width: 90%; margin: 0px; " id = "numeroLike<?= $valor['id'] ?>">  <img onclick = "remover_like(<?= $valor['id'] ?>)"  src="assets/img/coracao.png" style="width: 1.4rem;" /></p>
                                            </button>

                                      </div>
                                  </div>
                                  <?php }?>
                                  <div class="col-6">
                                      <div class = "text-center">
                                            <button class = "btn btn-light border border-primary" id = "like<?= $valor['id'] ?>"   style="width: 90%; margin: 10px; " onclick = "salvar(<?= $valor['id'] ?>,<?= $valor['id_usuario'] ?>)">
                                                <p style="width: 90%; margin: 0px; " id = "numeroSalvar<?= $valor['id'] ?>"> <img  src="assets/img/salve.png" style="width: 1.4rem;" /></p>  
                                                
                                            </button>
                                      </div>
                                  </div>
                                  
                              </div> 
                              <div class="row">
                                  
                                    <div class="col-12">
                                        <div class = "text-center" id = "postagem_<?= $valor['id'] ?>" >

                                        <a href="/comentarios?id=<?= $valor['id'] ?>&destino=turma&nome_turma=<?= $this->view->dados_turma[0]['nome_turma'] ?>&id_turma=<?= $_GET['id_turma'] ?>">
                                          <button class = "btn btn-light border border-primary" style="width: 95%; margin: 10px; " type="submit"  >
                                            <img style="width: 1.5rem;" class="text-center" src="assets/img/responder2.png" alt="">
                                          </button>
                                        </a>
                                          
                                         
                                        </div>
                                    </div>
                                </div>
                              <?php  }?>
                              </div>
                            </div>
                    </div>
                <?php $cont++;  }?>
                   <!-- ======= FIM DO CARD DE POSTAGEM ======= -->

                          </div>
                        </div>
                    </div>
                  </div>

                </div>
              </div>  
          <!-- ======= FIM DA AREA ONDE VC VE TODAS AS POSTAGEM ======= -->


          </div>
                  
            </div>
        </div>
    
        <!-- ======= SENSSÃO ======= -->
        <!-- ======= SENSSÃO ======= -->
        <!-- =======   FIM   ======= -->
        <div class="modal fade" id="sobre" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Sobre</h5>
       
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="row">
      <div class="col-lg-12"">
              <div class=" mb-3">
                <div class="row m-3" >
                  <div class="col-12">
                    <div class=" align-items-stretch text-center" data-aos="fade-up" data-aos-delay="100">
                    <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $this->view->dados_turma[0]['foto_turma'] ?>" style="width: 8rem;" />
                          <h3 style = "color: black;"><?= $this->view->dados_turma[0]['nome_turma'] ?></h3>
                          <p><?= $this->view->dados_turma[0]['descricao_turma'] ?></p>
                    </div>
                  </div>
                </div>
              </div>
          <?php if($this->view->dados_turma[0]['id_adm'] == $_SESSION['id']){  ?>
            <small class = "d-none d-lg-block"><b>Meus Alunos</b></small>
            <?php
                  if(count($this->view->listar_alunos) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="">
                        <p><small>Ainda não tens nenhum aluno para listar!</small></p>
                        </center>
                       
                    <?php } else { foreach($this->view->listar_alunos as $key => $valor){  ?>
                        <div class="mb-3" id = "aluno<?= $valor['id'] ?>">
                        <div class="row" >
                            <div class="col-12">
                            <div class=" align-items-stretch" data-aos-delay="100">
                                    <a>
                                        <div class="row mt-2 ml-1">
                                        <div class="col-2">
                                        <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>" style="width: 3rem; margin-left: 0px;" />
                                        </div>
                                        <div class="col-7">
                                            <p style="margin-top: 8%;"><?= $valor['nome'] ?></p>  
                                        </div>
                                        <div class="col-2">
                                            <img onclick = "add_turma(<?= $valor['id'] ?>,<?= $this->view->dados_turma[0]['id_turma'] ?>)"  src="assets/img/turma/add.png" style="width: 2rem;" />
                                        </div>
                                        
                                        </div>
                                    </a>  
                            </div>
                            </div>
                        </div>
                        </div>
                    <?php }}?>
                    <small class = "d-none d-lg-block"><b>Minhas turmas</b></small>
                      <?php  foreach($this->view->turma as $key => $valor){ ?>
                          <div class="row mt-3">
                              <div class="col-2  mr-3">
                                <img class="rounded-circle border border-primary m-1" src="/fotos_de_perfil/<?= $valor['foto_turma'] ?>" style="width: 3rem;" />
                              </div>
                            <div class="col-7">
                              <p style = "margin-top: 10%;" class = "d-none d-lg-block"><?= $valor['nome_turma'] ?></p>  
                            </div>
                            <div class="col-1" style = "margin-top: 4%;">    
                              <div class="row" >
                              <a href = "/entrar_turma?id_turma=<?= $valor['id_turma'] ?>">
                                  <img src="/assets/img/sobre_pessoal/entrar.png" style="width: 2rem;" />
                                </div>
                              </a>
                            </div>
                          </div>
                      <?php  } ?>

                     <small class = "d-none d-lg-block mt-3"><b>Carregar Foto De Perfil</b></small>
                        <div class="row mb-5" >
                            <div class="col-12">
                            <div class=" align-items-stretch" data-aos-delay="100">
                            <div class="row">
                              <form class = "m-2" action="/carregar_foto_perfil" method="post" enctype = "multipart/form-data">
                              <div class="row m-auto">
                                  <div class="col-8">
                                    <input id = "imagem" class = "uploadbox" name = "imagem" type="file">
                                  </div>
                                  <div class="col-4">
                                  <input type="hidden" name = "turma" value = "<?= $this->view->id_turma ?>">
                                              
                                    <button style = " width: 100%;" class = "btn btn-primary" type="submit">
                                      +
                                    </button>
                                  </div>
                                                
                                </div>
                              </form>
                            </div>
                            </div>
                        </div>
                        </div>
                         <?php }?>

        </div>
      </div>
      </div>
          
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
    
<div class="modal fade" id="membros" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Membros</h5>
       
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="col-lg-12">
                    <b>Membros</b>
                    <?php
                  if(count($this->view->listar_membros) < 1)
                  {
                    ?>
                    <center class = "mt-5">
                        <img src="assets/img/vazio.png" alt="" style="margin-top: 40%;">
                        <p><small>Ainda não tens nenhum membro nesta turma!</small></p>
                        </center>
                       
                    <?php } else { foreach($this->view->listar_membros as $key => $valor){  ?>
                      <div class=" mb-3">
                      <div class="row" id = "aluno<?= $valor['id'] ?>">
                          <div class="col-12">
                          <div class=" align-items-stretch" data-aos-delay="100">
                                      <div class="row mt-2 ml-1">
                                      <div class="col-2">
                                      <img class="rounded-circle border border-primary" src="/fotos_de_perfil/<?= $valor['nome_foto'] ?>"  style="width: 2.5rem; height: 2.5rem; object-fit: cover;" />
                                      </div>
                                      <div class="col-7">
                                          <p style="margin-top: 8%;"><?= $valor['nome'] ?></p>  
                                      </div>
                                      <?php if($this->view->dados_turma[0]['id_adm'] == $_SESSION['id']){  ?>
                                      <div class="col-2">
                                            <img onclick = "remove_turma(<?= $valor['id'] ?>,<?= $this->view->dados_turma[0]['id_turma'] ?>)"  src="assets/img/turma/remove.png" style="width: 2rem; cursor: pointer;" />
                                        </div>
                                        <?php } ?>
                                      </div>
                          </div>
                          </div>
                      </div>
                      </div>
                  <?php }}?>
                        
                        
                    </div>
      </div>
          
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
    

    

    

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
