<html>
	<head>
		<meta charset="utf-8" />
		<title>TeacherUs</title>
		<link rel="icon" type="image/png" href="./img/teach.png" />
		<link rel="stylesheet" type="text/css" href="cssClaro/style.css">
		<link rel="stylesheet" type="text/css" href="cssClaro/Animate.css">
		<link rel="stylesheet" type="text/css" href="cssClaro/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="cssClaro/b4_sidebar.css">

		<script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.js"></script>	
		<script type="text/javascript" src="js/b4_sidebar.js"></script>	
		<link rel="stylesheet" href="/cssClaro/style.css" />
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">	

	</head>
	<body style = "background-color: #F0F2F5;">
	

  <!-- End Header -->
		<?= $this->content() ?>
	</body >

</html>