<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Chat</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
   

    <link rel="icon" type="image/png" href="asset/img/favicon.png" />
    <link type="text/css" rel="stylesheet" href="asset/style/homepage.css">
    <link type="text/css" rel="stylesheet" href="asset/style/inbox.css">
    <link type="text/css" rel="stylesheet" href="asset/style/chat.css">
    <link type="text/css" rel="stylesheet" href="asset/style/profile.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
    <script src="asset/js/jquery.js"></script>

     <!-- Other imports -->
     <script src="asset/js/sweetalert2.js"></script>
    <link rel="stylesheet" href="asset/style/sweetalert2.css">
</head>
<body>
    
<?= $this->content() ?>
</body>
</html>